### ISSUE TITLE
website pageview analytics

### ISSUE THREAD

**Issue by philips** [etcd-io/website#10]
To help figure out the effectiveness of the etcd documentation and marketing pages we need to provide analytics such as page views, bounce rates, time on page, and geographic information.

**Comment by lucperkins** [comment]
@philips Do you have an existing Google Analytics account that you’d like to utilize?

**Comment by philips** [comment]
No, we do not

**Comment by philips** [comment]
It doesn't need to be Google Analytics either. Does the CNCF have a standard solution?

**Comment by lucperkins** [comment]
@philips We typically use Google Analytics. I'll work through internal channels to get you a project account.

**Comment by philips** [comment]
Any update on this? Will the etcd maintainers be able to have admin access to the Google Analytics?
