### ISSUE TITLE
RFC: New Information Architecture

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#110]
As per the conversation around the [Etcd.io Docs/SEO Improvement Plan](https://github.com/etcd-io/website/issues/65), I've put together an Information Architecture to help guide the website changes and development of new pages on the site. I'm sharing it here as we discussed in the [March 11, 2021 etcd public meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#heading=h.2pcfcuck4vc) to invite comment and critique.

**Proposed Information Architecture**: https://miro.com/app/board/o9J_lWnPo9c=/  
(I've also put together a diagram of the site's [current information architecture](https://miro.com/app/board/o9J_lX9eUAg=/) if you'd like to compare/contrast).

The idea behind the 4 top level branches are: 
* **Evaluation**: What is this product, is it right for me, what problem does it solve, and how will I know?
  * Sample section titles: Overview, Getting Started, Reference, Community
* **Addition**: How do I build solutions?
  * Section titles: API reference
* **Fix**: How do I fix problems I encounter?
  * Section titles: troubleshooting, FAQ
* **Features**: How do I build new features and contribute to the project?
  * Section titles: Contributing

(Thanks @zacharysarah for helping me map these)

**Comment by nate-double-u** [comment]
An invitation for comment:
@spzala @jberkus @gyuho @jingyih @ptabor @xiang90 @jpbetz @hexfusion

**Comment by nate-double-u** [comment]
I'd like to propose a lazy consensus here. If no one objects or comments by 5:00 PM PST on Friday, April 2, 2021, I'll go ahead and start work as laid out in this proposed architecture.

**Comment by ptabor** [comment]
Thank you, Nate:

Are the "Themes" user visible or just internal conceptual grouping. It's not intuitive to me that 'Addition' = building solution on top of etcd vs contributing to etcd,
Maybe we should call sections by the target audience explicitly: 
   - Getting started
   - For users
     - Administration
     - Reference docs
     - Trouble-shutting
     - Solutions
   - For contributors   
      - e.g https://etcd.io/docs/next/branch_management/ lands here

**Comment by nate-double-u** [comment]
> Are the "Themes" user visible or just internal conceptual grouping.

I think they are an internal conceptual grouping -- something that will inform how we restructure individual pages (like the front page), and how we link to pages in the TOC pages that @jberkus has suggested in #65.

I'm happy to rename the top 4 branches (among other things) if it makes it clearer.

Another goal I have is to not break bookmarks during this improvement project -- so that means either adding a lot of redirects, or, leaving the underlying structure alone and apply this structure on the pages themselves.

**Comment by nate-double-u** [comment]
I've re-done the colour scheme on the new IA diagram
* pink = new pages/sections
* orange = moved (in relation to their peer pages)
* green = no change (in relation to their peer pages)

**Comment by nate-double-u** [comment]
Closing issue as it was a request for comment, and we've had some  feedback. Thanks!
