### ISSUE TITLE
Use latest version of Hugo to build the site

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#113]
As of the time of creating this issue, the latest [release](https://github.com/gohugoio/hugo/releases) is 0.81.0. The currently used version, 0.65.0, is too old for docsy@HEAD.

cc @nate-double-u -- let's discuss an upgrade strategy.

**Comment by chalin** [comment]
Also ensure that Netlify and Docker use the same Hugo version -- see, https://github.com/etcd-io/website/commit/1d7f38d24862efc22cb5ce671801a37f1604fa34#r48286087.

**Comment by chalin** [comment]
FYI: I've checked the site files generated with Hugo 0.65 vs. 0.81 and the only problem I noticed was #114. We should probably resolve #114 first.

**Comment by chalin** [comment]
Other than that, the Hugo upgrade fixes a number of Markdown mis-rendering.

For example, the columns with numbers in the [Benchmarks][] table are meant to be right-justified (according to the Markdown), yet they appear left-justified when compiled under 0.65:

> ![image](https://user-images.githubusercontent.com/4140793/111341576-07b8f680-8650-11eb-93be-48e18116256c.png)

Hugo 0.81 respects the Markdown:

> ![image](https://user-images.githubusercontent.com/4140793/111341748-2d460000-8650-11eb-8ef7-ded2c8f4d10b.png)



[Benchmarks]: https://etcd.io/docs/current/op-guide/performance/#benchmarks

**Comment by nate-double-u** [comment]
> We should probably resolve #114 first.

see https://github.com/etcd-io/website/pull/118

**Comment by chalin** [comment]
Thanks for moving things forward with #118, @nate-double-u!

**Comment by chalin** [comment]
/assign @nate-double-u 

(@spzala - I'm hoping that we can get maintainer access soon so that we can actually assign issues. Thanks)
