### ISSUE TITLE
Client feature matrix: link-only section headings cause problems

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#114]
Most section headings in [Client feature matrix (v3.3.12)][] and [Client feature matrix (v3.3.13)][] are links to corresponding API pages. For example, see https://github.com/etcd-io/website/blame/master/content/docs/v3.3.12/learning/client-feature-matrix.md#L23:

    ## [KV](https://godoc.org/go.etcd.io/etcd/clientv3#KV)

Generally speaking, this isn't good practice.

Specifically in our case, it causes the following problems under more recent versions of Hugo (#113) and when the site is built with docsy (#94):

- If you click a Table-Of-Contents (TOC) entry, like **KV**, you're redirected to an API page, rather than jumping to the corresponding in-page heading.
- Rendered heading anchors are unintuitive -- e.g., like `#kvhttpsgodocorggoetcdioetcdclientv3kv` rather than `#kv`.

[Client feature matrix (v3.3.12)]: https://etcd.io/docs/v3.3.12/learning/client-feature-matrix/index.html
[Client feature matrix (v3.3.13)]: https://etcd.io/docs/v3.3.13/learning/client-feature-matrix/index.html

cc @nate-double-u @zacharysarah

---

> <img width="1110" alt="Screen Shot 2021-03-16 at 11 43 53" src="https://user-images.githubusercontent.com/4140793/111338150-1520b180-864d-11eb-8817-a56c9340d0a2.png">

**Comment by spzala** [comment]
Sounds good. Thanks @chalin
