### ISSUE TITLE
Client feature matrix: copyedits, link updates, and CSS cleanup needed

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#119]
This is a followup to #114 & #118.

As a general rule, we shouldn't embed raw links in the documents -- unless the raw link is part of the document content (such as providing a sample URL).

My suggestions are, for each page, and each section:

- [ ] Remove the raw URL and instead add text like the following _after_ the **feature table**:

    > For details, see the [KV API reference](https://pkg.go.dev/go.etcd.io/etcd/clientv3#KV).

- [ ] Update all links that refer to `godoc.org`. E.g.:

  - From: https://**godoc.org**/go.etcd.io/etcd/clientv3#KV
  - To: https://**pkg.go.dev**/go.etcd.io/etcd/clientv3#KV

- [ ] Globally search-and-replace the unnecessary left-indent syntax in the table Markup: left-indentation is the default, and adding the extra syntax causes redundant CSS to be generated. E.g., 

  - Replace:
    `:-------|:--------------------|:--------------`
  - With:
    `--------|---------------------|---------------`

cc @spzala @zacharysarah

**Comment by chalin** [comment]
/assign @nate-double-u 

(@spzala - I'm hoping that we can get maintainer access soon so that we can actually assign issues. Thanks)

**Comment by chalin** [comment]
Actually, @spzala, if you have the necessary rights, can you grant us maintainer access to this repo?

**Comment by nate-double-u** [comment]
> /assign @nate-double-u

On it :)
