### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#121]
The etcd-io/etcd repo is licensed under [Apache 2.0](https://github.com/etcd-io/etcd/blob/master/LICENSE).

I suggest we both license the website under Apache 2.0, and the documentation under CC-BY-4.0.

I like how the [Keptn project has done this in their website repo](https://github.com/keptn/keptn.github.io/pull/718), adding 2 LICENSE files, one for the site, the other for docs, and explaining it in their [README file](https://github.com/keptn/keptn.github.io#license).

**Comment by chalin** [comment]
Oh, sorry, I can't seen this issue -- copying my comment, https://github.com/etcd-io/website/pull/122#issuecomment-804966314, to here:

> @nate-double-u et al.: FYI, on the grpc.io site of things, we stream-lined the licence(s), mainly because our .io websites _are_ documentation repos (vs. code repos), and any code that is present in the website is usually there in support of the docs. I.e., grpc.io now have only one license file: https://github.com/grpc/grpc.io/blob/main/LICENSE

**Comment by caniszczyk** [comment]
can we get the LICENSE file back here in the repo

**Comment by chalin** [comment]
@caniszczyk - are you ok with a single license file, as I suggested in my previous comment (for the reasons given)?

**Comment by caniszczyk** [comment]
fine with me, we just need something in the repo that is either Apache 2.0 or CC-BY by default

**Comment by chalin** [comment]
Thanks for the confirmation, I think that that is what @nate-double-u was waiting for.

**Comment by nate-double-u** [comment]
I've updated https://github.com/etcd-io/website/pull/122
