### ISSUE TITLE
Update the Netlify config so that previews are automatically built for the docsy branch

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#127]
Update the Netlify config so that previews are automatically built for the docsy branch, ensuring that the docsy branch is not indexed by search engines.

Contributes to: https://github.com/etcd-io/website/issues/126, https://github.com/etcd-io/website/issues/94

/cc @chalin

**Comment by nate-double-u** [comment]
Once we agree if #128 is needed or not, then I can add the `docsy` branch deploy in Netlfiy.

<img width="1046" alt="Screen Shot 2021-03-19 at 10 27 03 AM" src="https://user-images.githubusercontent.com/4453979/111824396-10bef780-88de-11eb-8c8b-f80e1f8e2225.png">

/cc @spzala

**Comment by nate-double-u** [comment]
With #128 merged, I've updated the Netlify settings as shown above. The next PR into the `docsy` branch should trigger a deployment preview build, with the x-robots-tag set.

I'll do a test PR to ensure this is running as expected.

**Comment by nate-double-u** [comment]
PR https://github.com/etcd-io/website/pull/129 verified that PRs to the `docsy` branch do trigger a deploy preview, and that the preview generated has the `x-robots-tag` set to `noindex` meaning that this work shouldn't interfere with the site's SEO.

**Comment by chalin** [comment]
@nate-double-u: IMHO, any `docsy` related commit/PR that doesn't impact site generation for `master` should be merged into `master`. That will help us keep the `docsy` branch as clean as possible, which, in turn, will help diminish the pains of repeated rebases (of `docsy` over `master`), and eventually the final merge of `docsy` into `master` (if/when that happens).

So, I'd suggest reopening this issue and closing it via a PR merge over `master`. Thoughts?

**Comment by nate-double-u** [comment]
> ... any `docsy` related commit/PR that doesn't impact site generation for `master` should be merged into `master`.
> ... I'd suggest reopening this issue and closing it via a PR merge over master.

I agree with this.

**Comment by chalin** [comment]
(Re-)closed by #136
