### ISSUE TITLE
Ensure that only the docs for actively selected version show up in the side-nav

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#135]
Contributes to #134

**Comment by chalin** [comment]
@nate-double-u: Actually, I think that we can get a different kind of left-nav that is less overwhelming, e.g., see the one for grpc.io: https://grpc.io/docs/:

> <img src="https://user-images.githubusercontent.com/4140793/112230981-39abf900-8c0c-11eb-94c7-e9ae4da77fd5.png" width=180>

**Comment by nate-double-u** [comment]
This might dovetail with the information architecture changes we're thinking about making with the Docs Improvement plan.

RFC on new architecture: https://github.com/etcd-io/website/issues/110

**Comment by nate-double-u** [comment]
closed with https://github.com/etcd-io/website/pull/213
