### ISSUE TITLE
Footer: streamline and bring closer to updated CNCF website guidelines

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#137]
Streamline the website footer and bring it closer to the updated [CNCF website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md). As an example of this see https://github.com/grpc/grpc.io/pull/716.

This can be done before and/or after #134.

**Comment by nate-double-u** [comment]
related: #207

**Comment by chalin** [comment]
Closed by #207
