### ISSUE TITLE
Use a Netlify _redirects file to hold redirects

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#138]
An advantage of using a [Netlify `_redirects` file][r] over putting redirect rules in a `netlify.toml`, is that you can now use the full power of Hugo's templating language to generate all or part of the contents programmatically. E.g., see https://github.com/grpc/grpc.io/blob/main/layouts/index.redirects.

[r]: https://docs.netlify.com/routing/redirects/

**Comment by chalin** [comment]
Oh, it's interesting to see that the config for this was already present:
https://github.com/etcd-io/website/blob/bee20df169f61082eb965d06b614a5383a960b49/config.toml#L133-L138

**Comment by nate-double-u** [comment]
> Oh, it's interesting to see that the config for this was already present:

That's probably my bad -- I think I added the ones in the netlify.toml.

**Comment by chalin** [comment]
No worries. Actually, the `netlify.toml` file needs to be fully cleaned out.
