### ISSUE TITLE
README: update / drop "releasing a new version of docs" section

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#144]
Since #93, I don't think that the following text from the [README.md](https://github.com/etcd-io/website/blob/master/README.md) is accurate anymore, right @nate-double-u?

> ## Releasing a new version of the etcd documentation
> 
> In order to add documentation for a version of etcd, you need to:
> 
> * Navigate to the `etcd-io/etcd` repo and checkout the tag for the version, for example `git checkout v3.3.12`.
> * Copy the `Documentation` directory from the main `etcd` repo into the `content/docs` directory of this repository, renaming the directory to match the version. Here's an example for (non-existing) version 4.3.2:
> 
>     ```bash
>     cp -rf /path/to/etcd-io/etcd/Documentation /path/to/etcd-io/website/content/docs/v4.3.2
>     ```
> 
> * In the `_index.md` file at the root of the new directory, update the `title` metadata to reflect the new version. The title should read `etcd version <new-version>`.
> * Add the version to the `params.versions.all` array in the [`config.toml`](./config.toml) configuration file.
> * If the version is meant to be the latest version of etcd, change the `params.versions.latest` parameter to the desired new version.
> * Submit a pull request with the changes.

**Comment by nate-double-u** [comment]
I agree, we'll need to update the README - i've added this issue to our omni-issue #134
