### ISSUE TITLE
Replace coreos by etcd-io as an organization in links into GitHub

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#146]
Etcd's home organization is no longer https://github.com/coreos but rather https://github.com/etcd-io. Update links accordingly.

For example:

- From: https://github.com/coreos/etcd/blob/master/client/v3
- To: https://github.com/etcd-io/etcd/blob/master/client/v3

**Comment by nate-double-u** [comment]
related: https://github.com/etcd-io/website/issues/87

**Comment by nate-double-u** [comment]
What should we do with the monitoring pages:
* https://etcd.io/docs/next/op-guide/monitoring/#debug-endpoint
* https://etcd.io/docs/v3.4/op-guide/monitoring/#debug-endpoint
* https://etcd.io/docs/v3.3/op-guide/monitoring/#debug-endpoint
* https://etcd.io/docs/v3.2/op-guide/monitoring/#debug-endpoint

The `coreos` mention here looks to be a report -- and both the `coreos` and `etcd` repos 404.
