### ISSUE TITLE
Revise Versioning Structure to MAJOR.MINOR

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#152]
During the [March 11, 2021 etcd public meeting ](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#heading=h.2pcfcuck4vc) the question of when to cut new docs releases came up, and consensus seemed to be on MAJOR.MINOR releases of the main code.

I suggest that we structure the documentation releases the same way. This would affect both the underlying folder structure, and the version displayed on the site.

| Existing version | Proposed version | Update completed |
| --- | --- | --- |
| `current` | `next` | [ ] https://github.com/etcd-io/website/pull/161 |
| `v3.4.0` | `v3.4` | [ ] https://github.com/etcd-io/website/pull/161 |
| `v3.3.13` | `v3.3` | ✅ https://github.com/etcd-io/website/pull/159 |
| `v3.3.12` | removed | ✅ https://github.com/etcd-io/website/pull/159 |
| `v3.2.17` | `v3.2` | ✅ https://github.com/etcd-io/website/pull/158 |
| `v3.1.12` | `v3.1` | ✅ https://github.com/etcd-io/website/pull/156 |
| `v2` | `v2.3` | ✅ https://github.com/etcd-io/website/pull/154 |

* _Note_: I'm not sure what the most recent version of `v2` is, will need to look it up before making the change. [edit] Looks like the last v2 release was [v2.3.7](https://github.com/etcd-io/etcd/releases/tag/v2.3.7). I've updated the table to reflect this.

Part of the rationale for this is to simplify the version selector code, as well as to bring the documentation in line with what the actual release cadence will be moving forward.

**Comment by nate-double-u** [comment]
@spzala @jberkus @gyuho @jingyih @ptabor @xiang90 @jpbetz @hexfusion @chalin

**Comment by ptabor** [comment]
That's LGTM. Thank you.

**Comment by hexfusion** [comment]
+1

**Comment by jpbetz** [comment]
+1

**Comment by gyuho** [comment]
+1

**Comment by nate-double-u** [comment]
Added a column to the table to track the work and PR numbers.

**Comment by nate-double-u** [comment]
`v3.3.13` ➔ `v3.3` and the removal of `v3.3.12` should be done at the same time. We can set the redirect for v3.3.12 to point at the new `v3.3`.

**Comment by nate-double-u** [comment]
A question came up while discussing issue #155: what should we do with `v3.4.0`? Currently it's slated to me made into `v3.4`, at which point it will be out of date.

There looks like there is an alpha `v3.5.0` version in the works, which probably should be what **current** reflects (if **current** is going to be **next**),  and the new `v3.4` should reflect the existing `v3.4.15` (which **current** is closest to now).

**Comment by ptabor** [comment]
I would assume that current is 3.4.
 
Majority of users are expecting to find by default the most up-to-date documentation about currently stable version. 

Only after stable release of 3.5.0, we should change 'current' to 3.5.0

**Comment by chalin** [comment]
@ptabor - Thanks. That sounds consistent with what we're proposing, see https://github.com/etcd-io/website/issues/155#issuecomment-807010227

**Comment by nate-double-u** [comment]
So, based on the conversation here and in #155, here's my plan:

During the for the `v3.4.0` ➔ `v3.4` move:
- [ ] move `v3.4.0` folder to `v3.4`
- [ ] update the "Docs" link on the front page to point to `v3.4`
- [ ] move `current` folder to `next`
- [ ] set the `next` folder to be draft, so it won't get published except in dev mode.
- [ ] update the redirects so that https://etcd.io/docs/current/ ➔ https://etcd.io/docs/latest/ (which will be https://etcd.io/docs/v3.4.0/)

**Comment by nate-double-u** [comment]
I've updated the table in the description to reflect the conversation had in #155.

**Comment by chalin** [comment]
Great job!

**Comment by nate-double-u** [comment]
Thanks everyone!
