### ISSUE TITLE
Clarify which versions the "current" docs are for

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#155]
Versions of the docs include the following:

- https://etcd.io/docs/current/
- https://etcd.io/docs/latest/, which redirects to v3.4.0 (as of the time of creating this issue)
- https://etcd.io/docs/v3.4.0/
- etc

What does the **current** version of the docs refer to? Are the docs meant to match [etcd-io/etcd](https://github.com/etcd-io/etcd) at:

- @HEAD
- latest **stable release**, which is [v3.4.15](https://github.com/etcd-io/etcd/releases/tag/v3.4.15) at the time of writing
- latest **development release**, which is [v3.5.0-alpha.0](https://github.com/etcd-io/etcd/releases/tag/v3.5.0-alpha.0)
- Something else (e.g., some in-between state)

Whatever it is, we should update the docs to make this clear.

Somewhat related: #152

**Comment by nate-double-u** [comment]
I'm glad you opened this issue, I was thinking about this earlier today, but wasn't quite sure how to present it.

**Comment by nate-double-u** [comment]
When I made **current** it was intended to be as up to date with etcd-io/etcd as possible. 
When a version was released, the idea was that you could just copy **current** over to a new folder (let's say **v3.4.15**), update the config.toml, and have a new version, and continue with **current** being as close to etcd-io/etcd as possible.

**Comment by chalin** [comment]
That makes sense.

Maybe, then, it would make more sense to name it "next"? That is what [Angular](https://angular.io/docs) does: 

> ![image](https://user-images.githubusercontent.com/4140793/112394387-06806d00-8cd3-11eb-91c8-e10a52fe8612.png)

Also, maybe the "default" docs should be the "latest".

**Comment by nate-double-u** [comment]
I'd be OK with that.

**Comment by nate-double-u** [comment]
> Maybe, then, it would make more sense to name it "next"? That is what [Angular](https://angular.io/docs) does:

I'd be OK with that.

> Also, maybe the "default" docs should be the "latest".

I had considered that as well. Whenever I see links to the docs in the etcd-io/etcd repo (comments, the odd readme), I've linked to **latest**. I'd be OK with making the **default** go there too.

**Comment by nate-double-u** [comment]
My question is: what should we do with `v3.4.0`? Currently it's slated to me made into `v3.4`, at which point it will be out of date.

There looks like there is an alpha `v3.5.0` version in the works, which probably should be what **current** reflects (if **current** is going to be **next**),  and the new `v3.4` should reflect the existing `v3.4.15` (which **current** is closest to now).

**Comment by chalin** [comment]
Was your previous comment meant for #152? If so, maybe move it there.

**Comment by chalin** [comment]
So the "current" docs feature wasn't there before you consolidated the docs into this repo?

I can think of two solutions. The first one is to rename it to "next" and add explanatory text stating that the docs are WIP. Or, simply not publish the "next" docs, since they're WIP anyways. Thoughts?

**Comment by nate-double-u** [comment]
> Was your previous comment meant for #152? If so, maybe move it there.

It's probably relevant there too, but it's here as part of my thought process of this issue. (I think this issue and #152 are pretty closely linked)

**Comment by nate-double-u** [comment]
> So the "current" docs feature wasn't there before you consolidated the docs into this repo?

Correct. (here's a deploy preview from just before i started working on this repo: https://deploy-preview-84--etcd.netlify.app/)
 
> I can think of two solutions. The first one is to rename it to "next" and add explanatory text stating that the docs are WIP. Or, simply not publish the "next" docs, since they're WIP anyways. Thoughts?

I think I'd be OK with renaming it, and marking it draft. We'd need to link the front page to `/latest/` and probably set a redirect for `/current` ➔ `latest`

@spzala @jberkus have you got any thoughts on `current`?

**Comment by ptabor** [comment]
It would be good if 'developers' had access to the 'next/head' docs as they should ideally contain: fresh design-docs.

But the 'latest/stable' should stay as the default.

**Comment by nate-double-u** [comment]
Thanks @ptabor, I've updated the plan over in https://github.com/etcd-io/website/issues/152#issuecomment-807213618, sorry to spread this over two issues, I just think they're pretty closely linked.

**Comment by chalin** [comment]
Closing now that we've decided what to do with `current`.
