### ISSUE TITLE
Copy `next` into `v3.4`

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#163]
Based on the conversation in https://github.com/etcd-io/website/issues/152, https://github.com/etcd-io/website/issues/155, and https://github.com/etcd-io/website/pull/161:

Should we copy `next` (previously `current`) into `v3.4` now? `next` has the updated descriptions that were introduced when we migrated the docs over from etcd-io/etcd, and I think `next` best represents the latest `v3.4` version.

_Originally posted by @nate-double-u in https://github.com/etcd-io/website/issues/161#issuecomment-807427766_

**Comment by nate-double-u** [comment]
@ptabor @chalin @spzala @jberkus

**Comment by chalin** [comment]
I guess that it depends if it contains 3.5 changes.

**Comment by nate-double-u** [comment]
> I guess that it depends if it contains 3.5 changes.

I don't think it does yet. I haven't seen any new PRs with 3.5 changes -- though please correct me if I'm wrong @ptabor

**Comment by nate-double-u** [comment]
I've updated the title and description of this issue for clarity.
