### ISSUE TITLE
Simplify section titles for docs and version landing pages

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#178]
- [ ] Most websites name the docs landing page simply **Documentation** or even **Docs**. Currently, the title is "The etcd documentation" -- given that this is the etcd website, there is an overemphasis here. 
- [ ] Similar remarks apply to the landing page for each version of the docs

This redundancy / overemphasis will become even more obvious with breadcrumbs under the docsy theme, that will read something like:

- **The etcd documentation** / **etcd version 3.4** / ...

IMHO, this could more simply be:

- **Docs** / **v3.4** / ...

(which will be even more significant as we get down into the doc tree).

**Comment by nate-double-u** [comment]
closing with https://github.com/etcd-io/website/pull/213
