### ISSUE TITLE
[meta] Milestones

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#210]
@nate-double-u - how about creating milestones like these:

- 21Q1-pre-docsy
- 21Q2-docsy
- 21Q3-post-docsy

The prefix indicates an approximate quarter of when the work was started and/or will be finished. There three milestones will help us better organize our work -- vs. only using (or not using) the `docsy` tag.

Thoughts?

**Comment by nate-double-u** [comment]
I've not used milestones in github yet, but agree, this seems like a good idea. Should I also open a kanban project board or is that too much at this point?

**Comment by chalin** [comment]
Kanban feels like too much for now, thanks.

**Comment by nate-double-u** [comment]
Milestones setup
