### ISSUE TITLE
This repo is 97.2% Roff, really?

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#217]
According to GitHub, this repo is 97.2% [Roff](https://en.wikipedia.org/wiki/Roff_(software)), which is probably just an indication that we have improper (or missing) file suffixes somewhere:

> <img src="https://user-images.githubusercontent.com/4140793/114591414-d8e66e00-9c57-11eb-9306-d8be96b4ad2e.png" width=300>

[These are the files](https://github.com/etcd-io/website/search?l=roff) that GH thinks are Roff files.

/milestone 21Q3-post-docsy

**Comment by nate-double-u** [comment]
Related: https://github.com/etcd-io/website/issues/164

**Comment by nate-double-u** [comment]
Closing as duplicate.
