### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by tacerus** [etcd-io/website#218]
Hello,

maybe I am too dumb to navigate - however after spending several minutes search your documentation, and finding all kinds of interesting information, I was unable to find a basic installation ("Getting started") guide. The most I found was how to compile and run the binary as well as details on the configuration syntax - great, but now what do I do with it?

Cheers,
Georg

**Comment by nate-double-u** [comment]
Hi Georg,

Thanks for this. We are going through a docs improvement project now, #65, and a getting started guide is definitely in the plans.
