### ISSUE TITLE
better adopters copy

### ISSUE THREAD

**Issue by philips** [etcd-io/website#23]
- [ ] point the link to https://github.com/etcd-io/etcd/blob/master/Documentation/production-users.md and https://github.com/etcd-io/etcd/blob/master/Documentation/integrations.md
- [ ] Highlight projects like m3, rook, patroni, trillian, coredns, and openstack instead of Cloud Foundry (which doesn't use it anymore AFAIK)

**Comment by lucperkins** [comment]
@philips I'm not familiar with m3 and my Google searches have been fruitless. Could you provide a link?

**Comment by dankohn** [comment]
https://eng.uber.com/m3/
