### ISSUE TITLE
Fix github links on docs pages

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#246]
Edit this page
Create child page

Currently these links are incorrect

for example, on https://etcd.io/docs/v3.4/rfc/v3api/,
Edit this page expected:
https://github.com/etcd-io/website/edit/master/content/en/docs/v3.4/rfc/v3api.md

Edit this page actual:
https://github.com/etcd-io/website/edit/docsy/content/en/docs/v3.4/rfc/v3api.md

Create child page expected:
https://github.com/etcd-io/website/new/master/content/en/docs/v3.4/rfc/v3api.md?filename=change-me.md&value=---%0Atitle%3A+%22Long+Page+Title%22%0AlinkTitle%3A+%22Short+Nav+Title%22%0Aweight%3A+100%0Adescription%3A+%3E-%0A+++++Page+description+for+heading+and+indexes.%0A---%0A%0A%23%23+Heading%0A%0AEdit+this+template+to+create+your+new+page.%0A%0A%2A+Give+it+a+good+name%2C+ending+in+%60.md%60+-+e.g.+%60getting-started.md%60%0A%2A+Edit+the+%22front+matter%22+section+at+the+top+of+the+page+%28weight+controls+how+its+ordered+amongst+other+pages+in+the+same+directory%3B+lowest+number+first%29.%0A%2A+Add+a+good+commit+message+at+the+bottom+of+the+page+%28%3C80+characters%3B+use+the+extended+description+field+for+more+detail%29.%0A%2A+Create+a+new+branch+so+you+can+preview+your+new+file+and+request+a+review+via+Pull+Request.%0A

Create child page actual:
https://github.com/etcd-io/website/new/docsy/content/en/docs/v3.4/rfc/v3api.md?filename=change-me.md&value=---%0Atitle%3A+%22Long+Page+Title%22%0AlinkTitle%3A+%22Short+Nav+Title%22%0Aweight%3A+100%0Adescription%3A+%3E-%0A+++++Page+description+for+heading+and+indexes.%0A---%0A%0A%23%23+Heading%0A%0AEdit+this+template+to+create+your+new+page.%0A%0A%2A+Give+it+a+good+name%2C+ending+in+%60.md%60+-+e.g.+%60getting-started.md%60%0A%2A+Edit+the+%22front+matter%22+section+at+the+top+of+the+page+%28weight+controls+how+its+ordered+amongst+other+pages+in+the+same+directory%3B+lowest+number+first%29.%0A%2A+Add+a+good+commit+message+at+the+bottom+of+the+page+%28%3C80+characters%3B+use+the+extended+description+field+for+more+detail%29.%0A%2A+Create+a+new+branch+so+you+can+preview+your+new+file+and+request+a+review+via+Pull+Request.%0A

**Comment by nate-double-u** [comment]
Fix: update https://github.com/etcd-io/website/blob/ae1b7f61eebbcffe633d0e8551b8995f55dcee62/config.toml#L99

**Comment by chalin** [comment]
For the record, this was the first post-docsy todo item listed in #134.

**Comment by nate-double-u** [comment]
closed by https://github.com/etcd-io/website/pull/248
