### ISSUE TITLE
can we lowercase "etcd" uniformly in the document?

### ISSUE THREAD

**Issue by tangcong** [etcd-io/website#266]
can we lowercase etcd uniformly in the document, so that it looks more beautiful and standardized? thanks.
![image](https://user-images.githubusercontent.com/2403673/116643477-bff1f280-a9a3-11eb-9a93-9e98d625766f.png)

**Comment by nate-double-u** [comment]
There are some instances of "Etcd" in the text which should probably be made lower case, but for the header I'd expect this to be a scss change somewhere.
