### ISSUE TITLE
Update the Setting a key section in the Download and build documentation

### ISSUE THREAD

**Issue by dpuig** [etcd-io/website#268]
Greetings, i'm using `etcdctl`, i was consulting the documentation and  saw this little detail
https://etcd.io/docs/next/dl-build/#setting-a-key

```
$ ./bin/etcdctl put foo bar
OK
```

We are using `etcdctl 3.2.26` and `set` should be the command for Set a Key

```
$ ./bin/etcdctl set foo bar
bar
```

**Comment by nate-double-u** [comment]
Thanks @dpuig

This may also affect the following pages:
* https://etcd.io/docs/v3.4/dl-build/#test-the-installation
* https://etcd.io/docs/v3.3/dl_build/#test-the-installation
* https://etcd.io/docs/v3.2/dl_build/#test-the-installation
* https://etcd.io/docs/v3.1/dl_build/#test-the-installation

**Comment by spzala** [comment]
@dpuig thanks for reporting @nate-double-u thanks for the ping - `set` was used in v2 api and replaced with `put` in the v3 long time back. The v2 api's not actively supported and most v2 specific docs are removed, so I don't see a need for adding it in the current docs and this was also discussed in the past.  The `set` and other v2 commands are mentioned in here https://github.com/etcd-io/etcd/blob/master/etcdctl/READMEv2.md and migration relation docs. Thanks! I would suggest to close this issue if it's OK. Thanks!  cc @gyuho @xiang90 @jingyih @ptabor
