### ISSUE TITLE
Prometheus metrics not supported on macOS

### ISSUE THREAD

**Issue by wpedrak** [etcd-io/website#272]
When docs https://etcd.io/docs/next/metrics/#prometheus-supplied-metrics states that prometheus is exporting bunch of `process_*` metrics, this is not true for darwin. It might be worth to mention it.

Context: https://github.com/etcd-io/etcd/issues/12899

**Comment by jmhbnz** [comment]
Looks like this is still an issue, as discussed in https://github.com/etcd-io/etcd/issues/12899 there is still no process collector for darwin here: https://github.com/prometheus/client_golang/tree/main/prometheus

Added `good-first-issue` and `help-wanted` as it would be a very quick fix to add a small note/disclaimer under this section that the process metrics are not supported as of today under Darwin.
