### ISSUE TITLE
[3.5] Add initial docs for experimental distributed tracing feature 

### ISSUE THREAD

**Issue by lilic** [etcd-io/website#280]
With https://github.com/etcd-io/etcd/pull/12919 merged, we want to add a new section for Experimental Distributed Tracing. Docs are not my strength but I can give it a shot, I was thinking of adding:
- Warning at the start that this is experiential and API and features might change
- Describe each flag
- Mention this supports OpenTelemetry collector but I don't think we should go too much into details around that as it's likely to change

I wonder if it would make sense to have a section just for Observability in the navigation? To group metrics, profiling, logging and now tracing under there? https://etcd.io/docs/next/ @nate-double-u @chalin what do you think?

cc @gyuho @ptabor @hexfusion

**Comment by gyuho** [comment]
I think we can add around https://github.com/etcd-io/website/blob/master/content/en/docs/next/op-guide/monitoring.md#prometheus as a section "Distributed tracing"?

> have a section just for Observability in the navigation

I think once we have those in monitoring doc, we can discuss separating them out with @nate-double-u @chalin ?

**Comment by lilic** [comment]
That sounds good, will work on this after 3.5 code freeze.
