### ISSUE TITLE
Update references to etcd-io/etcd master branch

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#284]
As the `master` branch in [etcd-io/etcd](https://github.com/etcd-io/etcd) is being renamed to `main`, the documentation will need to be updated throughout.

Related issues: https://github.com/etcd-io/etcd/issues/12949, https://github.com/etcd-io/etcd/pull/12956, #149, #282

**Comment by chalin** [comment]
I've tagged this as cleanup and of low priority since GH redirects any requests of a non-existant branch to the default branch. So we shouldn't get any 404s (and so isn't critical), but it will be nice to clean it up at some point.
