### ISSUE TITLE
Turn off wiki feature on etcd-io/website

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#290]
Since we aren't using it, and it doesn't really make sense to have the wiki feature turned on for this website, I suggest we turn it off.

I'd like to propose a lazy consensus here. If no one objects or comments by 5:00 PM PST on Friday, May 21, 2021, I'll go ahead and turn off the feature.

/cc @spzala @gyuho @chalin

**Comment by hexfusion** [comment]
+1 if someone would like to use it we can turn it back on.

**Comment by nate-double-u** [comment]
Wiki has been turned off.
