### ISSUE TITLE
Versions menu: visually distinguish page vs. version-home targets

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#296]
If you're on page P, the versions menu will contain links to P in all other versions that have such a page. When there is no such page for version vX.Y then ` /docs/vX.Y` is used as a target. Currently, there is no visual cue to distinguish between these, but there should be.

**Comment by nate-double-u** [comment]
I find myself hovering over the menu to see if there is another version of the current page. A visual distinction would be helpful.

**Comment by kapunahelewong** [comment]
I can help out here!

**Comment by nate-double-u** [comment]
Some pics to clarify:

On page https://etcd.io/docs/v3.5/quickstart/

![Screen Shot 2021-06-22 at 10 11 24 AM](https://user-images.githubusercontent.com/4453979/122970092-fa14ba80-d37c-11eb-9ebb-3ec6dad67737.png)
Note the subtle highlighting when hovering over a version. Also note the link in the lower left hand corner -- there is a v3.4 version of this page, so the menu links to that page.

![Screen Shot 2021-06-22 at 10 11 28 AM](https://user-images.githubusercontent.com/4453979/122970087-f97c2400-d37c-11eb-8018-b419108a8566.png)
Note the link in the lower left again, v3.3 doesn't have a version of the Quickstart page, so the menu links to the root of v3.3 instead.

The code that builds this drop-down menu is here: https://github.com/etcd-io/website/blob/main/layouts/partials/navbar-version-selector.html
