### ISSUE TITLE
Versions menu UX issue

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#304]
My original thought was that the Versions menu shouldn't take up real estate in the top nav if it isn't being shown. For example:

![Screen Shot 2021-05-21 at 2 27 31 PM](https://user-images.githubusercontent.com/4453979/119199904-7022ba80-ba7b-11eb-869a-6fbe5f19c164.png)

![Screen Shot 2021-05-21 at 2 27 50 PM](https://user-images.githubusercontent.com/4453979/119199911-73b64180-ba7b-11eb-92c3-42f583f4d6bc.png)

**Comment by chalin** [comment]
An alternative, which would be more consistent, would be to always display the **Versions** menu but make it inactive on pages where it doesn't apply.
