### ISSUE TITLE
Create a Community page

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#306]
- [ ] Create a Community page
- [ ] Add a link to this page to the top nav

**Comment by chalin** [comment]
From https://github.com/etcd-io/website/pull/313#issuecomment-848112696, @nate-double-u writes:

> Do we want to include slack in the "Join the conversation" section?
> 
> * [#etcd](https://kubernetes.slack.com/archives/C3HD8ARJ5) on Kubernetes slack
> * [#etcd-docs](https://cloud-native.slack.com/archives/C01SFAR0Q00) on CNCF slack

I was going to hold off on the Slack channels for this first iteration. For example, Kubernetes doesn't even mention Slack in their Community page: https://kubernetes.io/community/ (although it is in the footer).

Questions I have regarding `#etcd` on the Kubernetes Slack:

- Why is the #etcd channel on the Kubernetes Slack? Doesn't that make it a Kubernetes-based channel?
- Shouldn't it be moved to either a CNCF Slack or it's own Slack?
- How actively is this channel monitored?

**Comment by nate-double-u** [comment]
> Questions I have regarding `#etcd` on the Kubernetes Slack:
> 
>     * Why is the #etcd channel on the Kubernetes Slack? Doesn't that make it a Kubernetes-based channel?
> 
>     * Shouldn't it be moved to either a CNCF Slack or it's own Slack?
> 
>     * How actively is this channel monitored?

These questions may constitute a whole new issue. There are [resources and tools](https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another) available if the project does want to move the `#etcd` channel from K8s slack to CNCF slack.

**Comment by chalin** [comment]
> These questions may constitute a whole new issue

Which is what I felt too, and why I didn't include them in the first version of the Community page.

**Comment by chalin** [comment]
We only recently created #etcd-docs, and it hasn't been getting any traffic since then. One suggestion is to close that (unused) channel and use GitHub discussions instead.
