### ISSUE TITLE
Developer Guide: API reference pages aren't listed for v3.4 and next

### ISSUE THREAD

**Issue by partcyborg** [etcd-io/website#315]
When viewing the etcd 3.3 API documentation on pages

https://etcd.io/docs/v3.3/dev-guide/api_reference_v3/
and
https://etcd.io/docs/v3.3/dev-guide/api_concurrency_reference_v3/

There is a warning at the top that says
```
Version v3.3 of the documentation is no longer actively maintained. The page that you are viewing is the last archived version. For the latest stable documentation, see v3.4.
```
However, if you go to the Developer guide for version 3.4, there are no links to the API documentation
https://i.postimg.cc/bwfXC6ML/Screen-Shot-2021-05-25-at-5-17-43-PM.png

Interestingly enough, the docs actually *are* there, if you manually change `v3.3` to `v3.4` in the URL
https://etcd.io/docs/v3.4/dev-guide/api_reference_v3/
https://etcd.io/docs/v3.4/dev-guide/api_concurrency_reference_v3/

**Comment by chalin** [comment]
Thanks for reporting this issue @partcyborg!

@nate-double-u: could you look into this? I believe that the v3.4 (and next, which seems to have the same issue) pages are missing front matter, and so aren't being picked up as pages in the section listing.

**Comment by chalin** [comment]
It might be worth checking if there are other pages without front matter.
