### ISSUE TITLE
Libraries and tools for v3.5 (next): add Scala reference

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#334]
> This change needs to be propagated to `/docs/next`, would you be willing to make that change @suizman? I'll open an issue to track this.

_Originally posted by @chalin in https://github.com/etcd-io/website/issues/286#issuecomment-849979206_

**Comment by suizman** [comment]
> > This change needs to be propagated to `/docs/next`, would you be willing to make that change @suizman? I'll open an issue to track this.
> 
> 
> 
> _Originally posted by @chalin in https://github.com/etcd-io/website/issues/286#issuecomment-849979206_

Feel free to make the changes. Thanks.
