### ISSUE TITLE
[Install page] 2 links going to the same place

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#347]
## Issue
On the _Install_ page, in the _Requirements_ section, the following bullet point copy link to the same page/section:
> * Supported platforms
> * Hardware recommendations

## Affected Pages
* https://etcd.io/docs/next/install/#requirements
* https://etcd.io/docs/v3.4/install/#requirements

**Comment by chalin** [comment]
Oops! Right, the first bullet should be a link to https://etcd.io/docs/next/op-guide/supported-platform, for the `next` page, with a similar link for the v3.4 page.
