### ISSUE TITLE
RCF v3 API page: keep/drop page, and/or change title

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#356]
Regarding http://etcd.io/docs/next/rfc/v3api/ (and http://etcd.io/docs/v3.4/rfc/v3api/):

- This was originally a Request For Comments (RFC) for the v3 API, right?
- Is this being kept for historical reasons?
- Does it still make sense to keep this page as part of the v3.5 docs?
- The current title is "Overview", which this page is not. It isn't even a complete RFC. At a minimum the title should be changed to reflect the context. If so, to what?
- Do you want an Overview page as part of the site? If so, which other page would be a good candidate?

These questions were originally asked at the [2021-06-03 etcd community meeting](https://docs.google.com/document/d/16XEGyPBisZvmmoIHSZzv__LoyOeluC5a4x353CX0SIM/edit#).

@gyuho - offered to follow up on answers.

**Comment by chalin** [comment]
There is no other candidate overview page (as reported by @gyuho? during the meeting). This is ok IMHO, since, at a minimum, the Quickstart page ends with a "what next?" list of suggestions.

**Comment by gyuho** [comment]
@chalin This is an initial draft by @xiang90 when we first proposed v3 API, and not actively maintained. I am ok with removing this in 3.5 and going forward, as long as we keep it in 3.4 and before docs.

**Comment by gyuho** [comment]
For reference, the original file can be found here https://github.com/etcd-io/etcd/blob/v3.4.16/Documentation/rfc/v3api.md and the initial commit is this https://github.com/etcd-io/etcd/commit/7c879ee57668f5f5a33dfa0443f4188e708ca030#diff-6f52d4f18616849f2359740b7e93cb658a25843a501316f3af371cff5b492ecf.

**Comment by chalin** [comment]
> removing this in 3.5 and going forward, as long as we keep it in 3.4 and before docs.

Ok, good.

> Since we don't have an owner to write the new technical overview page, can we just not have it for this release cycle?

Yes, let's do that.
