### ISSUE TITLE
Community: add link to etcd.cn

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#357]
Add a link to etcd.cn to the Community page, with a disclaimer that the site isn't officially endorsed by the etcd.io maintainers.

**Comment by chalin** [comment]
An example of how others have done it: https://dart.dev/community#additional-community-resources

**Comment by nate-double-u** [comment]
@kapunahelewong, this may be a good issue to get your development environment set up with.

**Comment by kapunahelewong** [comment]
Working on it now, thanks!!
