### ISSUE TITLE
Follow up to #359

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#361]
A few tweaks to the etcd.cn link on the community page:

- [ ] "version of this site" --> "translation of etcd.io"
- [ ] Put "(此...版)" inside / as part of the link text. Actually, use this text: "(本网站中文翻译)"
- [ ] ". Note that the Chinese language site is ..." --> "-- the website is ..."
- [ ] "by the etcd.io" --> "by etcd"

_Originally posted by @chalin in https://github.com/etcd-io/website/pull/359#discussion_r645120564_

**Comment by kapunahelewong** [comment]
I'll take it.
