### ISSUE TITLE
Add 3.3.13 docs

### ISSUE THREAD

**Issue by philips** [etcd-io/website#37]
@lucperkins are there docs on how to add a new release docs to the site?

https://github.com/etcd-io/etcd/releases/tag/v3.3.13

cc @gyuho

**Comment by lucperkins** [comment]
@philips There are instructions in the [README](https://github.com/etcd-io/website/#releasing-a-new-version-of-the-etcd-documentation) for this repo.

However, we will not be able to add new versions of the documentation until [this PR](https://github.com/etcd-io/etcd/pull/10615) goes through.
