### ISSUE TITLE
Create etcd-io fork of Docsy, point site theme at it

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#372]
Currently, the website `.gitmodules` points to the `etcd.io` branch of the CNCF fork of Docsy.

https://github.com/etcd-io/website/blob/d9716cbab88ab531deed4400853279a1b3ee55a1/.gitmodules#L1-L4

Ideally there should be a fork of Docsy in the etcd-io org, and the .gitmodules should point at that instead of the CNCF fork.

**Comment by chalin** [comment]
We had briefly discussed both options (branch vs full clone) at some point. More and more I'm in favor of the branch option (contrary to what I was advocating before 🤷‍♂️ 😄 ).

**Comment by chalin** [comment]
If you agree, let's consider closing this issue in favor of opening another to remind us to update the `etcd.io` branch of `cncf/docsy`.

**Comment by nate-double-u** [comment]
> If you agree, let's consider closing this issue in favor of opening another to remind us to update the `etcd.io` branch of `cncf/docsy`.

I agree, and was _just_ going to suggest the same.

**Comment by chalin** [comment]
The new issue is #431
