### ISSUE TITLE
[v3.5] Update snapshot restore to use `etcdutl snapshot restore`instead

### ISSUE THREAD

**Issue by lilic** [etcd-io/website#382]
We still reference `etcdctl snapshot restore ` which is deprecated as per CLI output:

```
etcdctl --endpoints=xyxyx snapshot restore snapshot.db
Deprecated: Use `etcdutl snapshot restore` instead.

```
We should change it to be `etcdutl` instead.

One example where we do this:
https://etcd.io/docs/v3.5/op-guide/recovery/#restoring-a-cluster

**Comment by lilic** [comment]
cc @ptabor

**Comment by gyuho** [comment]
I remember this was done so because of some dependency isolation. It would be good if we document why we decided to split this out in the first place.

**Comment by ptabor** [comment]
Thank you for noticing.  We look for the other changes in the webpage and prepare a PR. 

@gyuho :
Snapshot restore does not work over the wire, requires physical presence on the host where the files are and operates directly on the etcd file structure - so it belongs to `etcdutl`. 

`etcdctl` is CLI wrapper around client/v3

**Comment by lwille** [comment]
What's the status of this? Both etcd.io and kubernetes.io docs still reference the deprecated command, there's no install instructions for `etcdutl` (coming here from a killer.sh session).

**Comment by jmhbnz** [comment]
Closing - this was fixed by https://github.com/etcd-io/website/pull/576.
