### ISSUE TITLE
Some diagrams will really help in more understand. 

### ISSUE THREAD

**Issue by parveensh0** [etcd-io/website#385]
I really got confused with revisions and version.  And, if some sample example could be shared in the document. It will be really helpful atleast in the logical explanation.

**Comment by nate-double-u** [comment]
Hello @parveensh0, thanks for this report. 

Could you provide some more detail? 
* Which page was confusing you? 
* Which part of the system would you like to see an example of?

**Comment by chalin** [comment]
Closing. @parveensh0 - feel free to open another issue once you are ready to provide more detailed feedback.
