### ISSUE TITLE
Convert Platforms/Amazon Web Services page into a blog post

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#396]
Convert ["Platforms/Amazon Web Services" page](https://etcd.io/docs/v3.5/platforms/aws/) into a blog post, and remove it from v3.5 (and other versions moving forward).

This is a part of the discussion around "How to" type content (https://github.com/etcd-io/etcd/pull/12668#issuecomment-779665473)

**Comment by Somoshree** [comment]
"/assign"
