### ISSUE TITLE
not existing option `discovery-srv-name` is in the docs for 3.3.13 and .12

### ISSUE THREAD

**Issue by piontec** [etcd-io/website#40]
This option is described in the docs, but not supported in reality. Please check discussion here: https://github.com/etcd-io/etcd/issues/10916

**Comment by nate-double-u** [comment]
Pages affected:
* https://etcd.io/docs/v3.4/op-guide/clustering/#dns-discovery
* https://etcd.io/docs/v3.3/op-guide/clustering/#dns-discovery
* https://etcd.io/docs/next/op-guide/clustering/#dns-discovery

@spzala, is the solution here to remove the paragraph at the end of the _DNS discovery_ section that references `-discovery-srv-name` on these pages?
