### ISSUE TITLE
Configuration flag - the old flags "peer-ca-file" and "ca-file" should be removed

### ISSUE THREAD

**Issue by AndyYao17** [etcd-io/website#422]
We  found the two flags had been replaced by  "peer-trusted-ca-file" and "trusted-ca-file" on 20 Mar, 2018
The doc(version which newer than above) need to be updated.

**Comment by AndyYao17** [comment]
commits around this: 
https://github.com/etcd-io/etcd/commits/main?before=82ef3f83f6f63ee2f6203f056b9fdbb27f1c94f5+35&branch=main

**Comment by patrocinio** [comment]
Hello @AndyYao17, where do you see a reference to `peer-trusted-ca-file` and `trusted-ca-file` in the documentation?

**Comment by AndyYao17** [comment]
https://etcd.io/docs/v3.5/op-guide/configuration/#--peer-ca-file
This flag had been removed(not DEPRECATED) cuz it cannot works.
Is it better to be marked as 'REMOVED' or just deleted directly?
