### ISSUE TITLE
Error: must be run from 'go.etcd.io/etcd/v3' module directory

### ISSUE THREAD

**Issue by FedAnt** [etcd-io/website#425]
Hello!
Use this https://etcd.io/docs/v3.5/install/
in step #3 i have next error:
_./scripts/test_lib.sh: line 5: go: command not found
must be run from 'go.etcd.io/etcd/v3' module directory_

_./scripts/test_lib.sh: line 5: go: command not found_ -> decide `chown +x ./scripts/test_lib.sh`
_must be run from 'go.etcd.io/etcd/v3' module directory_ -> install golang `sudo apt install golang`

**Comment by patrocinio** [comment]
Hello @FedAnt,
    where do you see the instructions to run `./scripts/test_lib.sh` in the https://etcd.io/docs/v3.5/install/ page?

**Comment by jmhbnz** [comment]
Closing this stale issue. The etcd installation docs state that a minimum version of golang is required in order to build etcd from source.

> If you have [Go version 1.16+](https://golang.org/doc/install), you can build etcd from source by following these steps:
> ...

Note 1.16 is out of date as a pre requisite so I've raised https://github.com/etcd-io/website/pull/759.
