### ISSUE TITLE
FAQ broken link

### ISSUE THREAD

**Issue by somsubhro** [etcd-io/website#43]
the FAQ link [faq.md] is broken on readme.md. It is expecting a faq.md at: etcd.io/docs/v3.4.0/v2/readme/faq.md

**Comment by somsubhro** [comment]
Found that all of the links from the Documentation page is broken because of the extra "/readme/". Think all of them should point to ...v3.4.0/v2/xxxx.md

**Comment by chalin** [comment]
Thanks for reporting this, a fix is on the way!

@nate-double-u : can you assign this to me?
