### ISSUE TITLE
Install htmltest using it's install script once the next release becomes available

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#459]
To check links you'll need [htmltest](https://github.com/wjdp/htmltest/discussions)@HEAD in your path, unless you have `go` installed, then `npm run check-links` will fetch and build the required version for your. (That is, the current release 0.14.0 won't work.)

Otherwise, you can let Netlify check links for you as part of preview builds.

This issue is a reminder to update the `Makefile` to revert to using the htmltest install script once [a new release](https://github.com/wjdp/htmltest/discussions/174#discussioncomment-1209373) (>0.14) becomes available.

Context: https://github.com/etcd-io/website/blob/2a33bf51c2e58be8b5d2f22da2ec872bd8343c08/Makefile#L22-L37

**Comment by chalin** [comment]
I'm starting to think that we might want to keep that Makefile target renamed to, say, `build-link-checker`.

**Comment by dwelsch-esi** [comment]
This change seems to have been made in the website/Makefile. Can this issue be closed?

**Comment by jmhbnz** [comment]
> This change seems to have been made in the website/Makefile. Can this issue be closed?

Agree thanks for the prompt @dwelsch-esi. Closing.
