### ISSUE TITLE
Use new and better canonical link to Google Groups

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#479]
Instead of the following (with or without the `?hl=en`):

- https://groups.google.com/forum/?hl=en#!forum/etcd-dev

We can now use this canonical form, which is more link-checker friendly (since several checkers complain of a missing anchor target due to `#!forum...`):

- https://groups.google.com/g/etcd-dev

**Comment by chalin** [comment]
@xuan-nguyen-swe - yes. I'm seeing 34 more places where this needs to be fixed using this regex, `https?://groups.google.com/forum/(\?hl=en)?#!forum/etcd-dev`. Can you submit a PR?

**Comment by xuan-nguyen-swe** [comment]
@chalin sure, I will :)

**Comment by xuan-nguyen-swe** [comment]
@chalin totally I found [36 places in all repos](https://github.com/search?q=org%3Aetcd-io+++%22https%3A%2F%2Fgroups.google.com%2Fforum%22&type=code).

I am going to fix 28 places in "website" repo, which contains this ticket.
For other repos, could I link them to this ticket too?

![image](https://github.com/etcd-io/website/assets/24372782/4832efc4-4d1b-4204-ab4e-6c72b00a5e2e)

**Comment by xuan-nguyen-swe** [comment]
@chalin Funny, my IDE found 34 places like you mentioned for the "website" repo, but only 28 places from github search.

Could you please confirm my question in my previous comment, then I will continue on other repos.

**Comment by jmhbnz** [comment]
> Could you please confirm my question in my previous comment, then I will continue on other repos.

Hey @xuan-nguyen-swe, thanks for working on this, you can certainly use this issue to drive the updates on the other repos as well.

**Comment by xuan-nguyen-swe** [comment]
@chalin should we close this issue?

**Comment by jmhbnz** [comment]
Closing - Work has been completed, thanks @xuan-nguyen-swe 🙏🏻
