### ISSUE TITLE
Images not found in etcd docs

### ISSUE THREAD

**Issue by ChaitanyaKaranam** [etcd-io/website#48]
Images are not found in this etcd [doc](https://etcd.io/docs/v3.4.0/learning/design-client/)

![image](https://user-images.githubusercontent.com/26694932/65741340-5a73bb00-e109-11e9-81a4-a0d58d59c5a3.png)

**Comment by ChaitanyaKaranam** [comment]
Same issue with this [doc](https://etcd.io/docs/v3.4.0/learning/design-learner/)

**Comment by ChaitanyaKaranam** [comment]
I have found the location of these images. I will raise a PR shortly.

**Comment by ChaitanyaKaranam** [comment]
Should be fixed in this [PR](https://github.com/etcd-io/website/pull/49)

**Comment by nate-double-u** [comment]
Closing issue as the images are now found on the https://etcd.io/docs/v3.4/learning/design-client/ page.

![Screen Shot 2021-03-30 at 10 12 40 AM](https://user-images.githubusercontent.com/4453979/113028746-2c968900-917b-11eb-9a7a-4d1eafe3b854.png)
