### ISSUE TITLE
Multiple Broken Links across the site

### ISSUE THREAD

**Issue by ChaitanyaKaranam** [etcd-io/website#50]
There are multiple broken links across the site. I am working on fixing them. I have fixed most of external links.

Here's the current state of broken links - 
https://docs.google.com/spreadsheets/d/10FXHFFzSJy4NvezabBPvS5Bm8z3WhVQclz0RxI_aDUo/edit?usp=sharing

I could not find the links for the ones highlighted in red.

I am working on fixing remaining links.

**Comment by davidnuzik** [comment]
I've also noticed this. For example, https://github.com/etcd-io/website/edit/master/content/docs/v3.4.0/op-guide/security.md references a link near the top of the page " and we provide an example using the tool here" the "here" link is a dead link.

**Comment by nate-double-u** [comment]
Hi @ChaitanyaKaranam, I'm looking at fixing links as a part of the docs improvement plan #65. I've already built a PR (#174) to fix all the internal links, and am looking at doing external links soon.

Did you use a program to build your spread sheet? I've added a `make check-all-links` to track them, but am interested in how you built out your sheet as well.

**Comment by ChaitanyaKaranam** [comment]
> Hi @ChaitanyaKaranam, I'm looking at fixing links as a part of the docs improvement plan #65. I've already built a PR (#174) to fix all the internal links, and am looking at doing external links soon.
> 
> Did you use a program to build your spread sheet? I've added a `make check-all-links` to track them, but am interested in how you built out your sheet as well.

I ran it through https://www.deadlinkchecker.com/website-dead-link-checker.asp it crawls through website and generates report. I used `https://etcd.io/docs/` as input to check all the dead links

**Comment by nate-double-u** [comment]
Thanks for that. I've run it again, and it looks like we're down to 32 broken links, down from 327! 

https://docs.google.com/spreadsheets/d/1TWDL6RHCEQiPK1G3PJcpne8UK74Eb2ZoCGOSoTBBECw/edit?usp=sharing

**Comment by nate-double-u** [comment]
Though, when I run `make check-all-links` I get significantly more errors. So there's still some work to be done.

```
➜  etcd-io-website git:(master) make check-all-links
npm run production-build

⋮

> production-build
> hugo --cleanDestinationDir --minify

Start building sites …

                   | EN
-------------------+------
  Pages            | 451
  Paginator pages  |   0
  Non-page files   | 170
  Static files     |  32
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Total in 1525 ms

⋮

bin/htmltest --conf .htmltest.external.yml
htmltest started at 10:54:21 on public
========================================================================
blog/jepsen-343-results/index.html
  Non-OK status: 416 --- blog/jepsen-343-results/index.html --> https://fauna.com/blog/demystifying-database-systems-part-4-⋮

⋮

/version.go#L30
  Non-OK status: 404 --- docs/v3.2/dev-internal/release/index.html --> https://github.com/coreos/etcd%22
  Non-OK status: 404 --- docs/v3.2/dev-internal/release/index.html --> https://github.com/coreos/etcd%22
  Non-OK status: 404 --- docs/v3.2/dev-internal/release/index.html --> https://github.com/coreos/etcd/blob/master/version/version.go#L30
========================================================================
✘✘✘ failed in 2m30.47436296s
159 errors in 403 documents
make: *** [Makefile:26: check-all-links] Error 1
```

**Comment by ChaitanyaKaranam** [comment]
> Though, when I run `make check-all-links` I get significantly more errors. So there's still some work to be done.
> 
> ```
> ➜  etcd-io-website git:(master) make check-all-links
> npm run production-build
> 
> ⋮
> 
> > production-build
> > hugo --cleanDestinationDir --minify
> 
> Start building sites …
> 
>                    | EN
> -------------------+------
>   Pages            | 451
>   Paginator pages  |   0
>   Non-page files   | 170
>   Static files     |  32
>   Processed images |   0
>   Aliases          |   0
>   Sitemaps         |   1
>   Cleaned          |   0
> 
> Total in 1525 ms
> 
> ⋮
> 
> bin/htmltest --conf .htmltest.external.yml
> htmltest started at 10:54:21 on public
> ========================================================================
> blog/jepsen-343-results/index.html
>   Non-OK status: 416 --- blog/jepsen-343-results/index.html --> https://fauna.com/blog/demystifying-database-systems-part-4-⋮
> 
> ⋮
> 
> /version.go#L30
>   Non-OK status: 404 --- docs/v3.2/dev-internal/release/index.html --> https://github.com/coreos/etcd%22
>   Non-OK status: 404 --- docs/v3.2/dev-internal/release/index.html --> https://github.com/coreos/etcd%22
>   Non-OK status: 404 --- docs/v3.2/dev-internal/release/index.html --> https://github.com/coreos/etcd/blob/master/version/version.go#L30
> ========================================================================
> ✘✘✘ failed in 2m30.47436296s
> 159 errors in 403 documents
> make: *** [Makefile:26: check-all-links] Error 1
> ```
> 
> I've shared the whole report on the second sheet of the https://docs.google.com/spreadsheets/d/1TWDL6RHCEQiPK1G3PJcpne8UK74Eb2ZoCGOSoTBBECw/edit?usp=sharing spreadsheet.

This looks much better. This should work.
