### ISSUE TITLE
Revise and expand Installation docs

### ISSUE THREAD

**Issue by jberkus** [etcd-io/website#509]
Our installation docs need to cover all of the ways that people install etcd for production.  We should create subheads under installation for each of the following installation techniques:

- Installation via pre-built binaries, which is the doc now (but see #506)
- Build from source, also already doc'd
- Installation via OS packages
- Installation as part of Kubernetes installation (kubeadm?  any others?)
- Installation *on* Kubernetes, using a statefulset or helm chart 
- Any other common methods?

For now, @Somoshree can stub most of these out so that they can be filled in later.

**Comment by jmhbnz** [comment]
Stubs were aded in #534 so closing this in favor of the new tech docs issue for the remaining work to add content to the linux section https://github.com/etcd-io/website/issues/767.
