### ISSUE TITLE
dev-guide:  go get github.com/mattn/goreman failed

### ISSUE THREAD

**Issue by linsite** [etcd-io/website#563]
page: https://etcd.cn/docs/current/dev-guide/local_cluster/

$ go version                                                                                                                                          
go version go1.17.2 linux/amd64

$ go get github.com/mattn/goreman
go: downloading github.com/mattn/goreman v0.3.9
go: downloading github.com/joho/godotenv v1.3.0
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e
go: downloading gopkg.in/yaml.v2 v2.2.7
go: downloading github.com/mattn/go-isatty v0.0.10
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Comment by jmhbnz** [comment]
Hey @linsite - Thanks for reporting this issue and apologies you did not receive a reply earlier, the etcd project has not had enough contributors to respond to all issues.

I've raised #663 to fix the goreman installation instructions.
