### ISSUE TITLE
Want to publish a helm chart deployment tutorial

### ISSUE THREAD

**Issue by zhangtong007** [etcd-io/website#573]

**Comment by jmhbnz** [comment]
Filling in the installation gaps on our website to cover helm would be a great first issue: https://etcd.io/docs/v3.6/install/#installation-on-kubernetes-using-a-statefulset-or-helm-chart 

We would need to decide if we will maintain a chart ourselves or just suggest people use a third party chart like https://bitnami.com/stack/etcd/helm.

Given constraints in terms of maintaining existing codebase and trying not to add new code we need to maintain it might be best to suggest a third party chart for now.

**Comment by jmhbnz** [comment]
Completed via #670, thanks @chrsalx
