### ISSUE TITLE
Error: grpc: timed out when dialing,

### ISSUE THREAD

**Issue by 809544928** [etcd-io/website#575]
Excuse I want to ask that what the means of "be sure to use the new varibale names……（link）"
That is how to solve this problem.

etcdctl environment variables have been updated. If ETCDCTL_API=2 etcdctl cluster-health works properly but ETCDCTL_API=3 etcdctl endpoints health responds with Error: grpc: timed out when dialing, be sure to use the [new variable names](https://github.com/etcd-io/etcd/tree/v3.1.20/etcdctl#etcdctl)

**Comment by jmhbnz** [comment]
Hi @809544928 - Thanks for raising this question. Apologies it has taken so long for anyone to respond, the etcd project has not had enough contributors to respond to all issues.

In short, the message is informing you that the environment variable names for etcdctl have been updated and you need to make sure that you are using the new variable names in your commands or scripts if you want to use ETCDCTL_API=3.

The new variables names are documented in the `etcdctl` README.md: https://github.com/etcd-io/etcd/blob/main/etcdctl/README.md#etcdctl. 

I'll close this issue now but if you still have any questions about this or something isn't clear please let me know.
