### ISSUE TITLE
The v3.5 documentation also provides instructions on logging using capnslog.

### ISSUE THREAD

**Issue by dc7303** [etcd-io/website#605]
I was able to check in the [ETCD config file](https://github.com/etcd-io/etcd/blob/a3b410cac74d6b0082ad3e40ba384b8650a809e4/server/embed/config.go#L376-L377) that capnslog is not used since v3.5. But the docs are still stating that they are using capnslog. Is this correct?

https://etcd.io/docs/v3.5/dev-internal/logging/
> etcd uses the `capnslog` library for logging application output categorized into levels.

**Comment by jmhbnz** [comment]
/assign

Thanks for reporting this @dc7303, I have raised a pull request to correct this.
