### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#620]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by spzala** [comment]
@nate-double-u I actually just noticed it while working on a PR and I was about to open an issue and ping you that if you can help with it ?

**Comment by spzala** [comment]
Also, copying @chalin

**Comment by nate-double-u** [comment]
Hi @spzala, I'm happy to help out here!

**Comment by spzala** [comment]
Thank you so much, Nate! @nate-double-u

**Comment by nate-double-u** [comment]
Updated to Ubuntu 20.04 (default)

<img width="920" alt="Screen Shot 2022-10-05 at 11 44 20 AM" src="https://user-images.githubusercontent.com/4453979/194138281-157034d0-d8b1-4a58-9d65-91e88418f32d.png">

Now we're getting another deprecation warning:
> WARNING: Your site had a deprecated version of Ruby pinned (2.3.6), which is incompatible with this
build image. This build image only supports 2.4.x and later. We changed it to 2.7.2.
>
> To learn how to set a custom Ruby version, visit the following link:
https://docs.netlify.com/configure-builds/manage-dependencies/#ruby
>
> If you set a custom Ruby version lower than 2.4.x, you will need to select a different build image (Ubuntu Xenial 16.04).
> The current build image only supports 2.4.x and later. You can select a different build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection

The site still builds and deploys correctly. We should go through and make sure that our Ruby version isn't causing issues.

**Comment by spzala** [comment]
Awesome!!! Thanks @nate-double-u

**Comment by spzala** [comment]
fyi @serathius @ahrtr @ptabor
