### ISSUE TITLE
request cluster ID mismatch

### ISSUE THREAD

**Issue by QiuToo** [etcd-io/website#625]
When I deploy the etcd 3.5.5 high availability cluster, the relevant nodes cannot be started.
root@two-node2 ~]# etcd -version
etcd Version: 3.5.5
Git SHA: 19002cfc6
Go Version: go1.16.15
Go OS/Arch: linux/amd64
[root@two-node2 ~]# 
######################
[root@two-node2 ~]# cat  /etc/etcd/etcd.conf 
#[Cluster tag]
ETCD_INITIAL_CLUSTER="etcd-1=https://192.168.2.31:2380,etcd-2=https://192.168.2.32:2380,etcd-3=https://192.168.2.33:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.2.33:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.2.33:2379"
#[Member tag]
ETCD_NAME="etcd-3"
ETCD_DATA_DIR="/var/lib/etcd"
ETCD_HEARTBEAT_INTERVAL="100"  
ETCD_ELECTION_TIMEOUT="1000"
ETCD_LISTEN_PEER_URLS="https://192.168.2.33:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.2.33:2379,https://127.0.0.1:2379"
#[Safety mark]
ETCD_CLIENT_CERT_AUTH=true
ETCD_PEER_CERT_FILE="/etc/kubernetes/pki/etcd/etcd.pem"
ETCD_PEER_KEY_FILE="/etc/kubernetes/pki/etcd/etcd-key.pem"
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_TRUSTED_CA_FILE="/etc/kubernetes/pki/ca.pem"
ETCD_PEER_AUTO_TLS="true"
ETCD_CERT_FILE="/etc/kubernetes/pki/etcd/etcd.pem"
ETCD_KEY_FILE="/etc/kubernetes/pki/etcd/etcd-key.pem"
ETCD_CLENT_CERT_AUTH=true
ETCD_TRUSTED_CA_FILE="/etc/kubernetes/pki/ca.pem"
ETCD_AUTO_TLS="true"

######################
The log is as follows:
11月 08 09:58:48 two-node2 etcd[18720]: {"level":"warn","ts":"2022-11-08T09:58:48.682+0800","caller":"rafthttp/http.go:500","msg":"request cluster ID mismatch","local-member-id":"b3beb954340f5da5","local-member-cluster-id":"c3399db74b22a3e","local-member-server-version":"3.5.5","local-member-server-minimum-cluster-version":"3.0.0","remote-peer-server-name":"13e80a3a18a899a","remote-peer-server-version":"3.5.5","remote-peer-server-minimum-cluster-version":"3.0.0","remote-peer-cluster-id":"5a452912fedf1f6e"}
11月 08 09:58:48 two-node2 etcd[18720]: {"level":"warn","ts":"2022-11-08T09:58:48.685+0800","caller":"rafthttp/http.go:500","msg":"request cluster ID mismatch","local-member-id":"b3beb954340f5da5","local-member-cluster-id":"c3399db74b22a3e","local-member-server-version":"3.5.5","local-member-server-minimum-cluster-version":"3.0.0","remote-peer-server-name":"13e80a3a18a899a","remote-peer-server-version":"3.5.5","remote-peer-server-minimum-cluster-version":"3.0.0","remote-peer-cluster-id":"5a452912fedf1f6e"}

**Comment by jmhbnz** [comment]
Closing this stale issue - General etcd support requests are managed via etcd discusssions: https://github.com/etcd-io/etcd/discussions

@QiuToo - Sorry this did not receive a timely response, if you are still encountering issues please let us know via our discussion forum.
