### ISSUE TITLE
Should "etcd put" be "etcd set" ?

### ISSUE THREAD

**Issue by agardnerIT** [etcd-io/website#639]
[The quickstart page](https://etcd.io/docs/v3.5/quickstart/) suggests a command: `etcdctl put greeting "Hello, etcd"`

Shouldn't that be: `etcdctl set greeting "Hello, etcd"`

If yes, I'll create a PR to fix.

**Comment by jmhbnz** [comment]
Hey @agardnerIT - Unless I'm missing something I believe `put` is the correct verb, see below:

```bash
james   main  
 ➜ ./etcdctl set
Error: unknown command "set" for "etcdctl"

Did you mean this?
        get
        put
```

**Comment by jmhbnz** [comment]
Hey @ahrtr, @spzala I think this one can be closed as `put` is definitely the correct verb.

**Comment by serathius** [comment]
Put is correct, please test commands before.
