### ISSUE TITLE
Typo in Figure 6. "etcd learner design" Quorum Lost section

### ISSUE THREAD

**Issue by kwangh** [etcd-io/website#647]
https://etcd.io/docs/v3.5/learning/design-learner/#24-quorum-lost
In Figure 6 No 2. the script is written "Requires 3 active follower, ...". However it seems 2 is right in this case since the quorum size is 3 (1 leader, 2 follower).

![image](https://user-images.githubusercontent.com/8899396/222128418-3718b565-390c-47ca-bafb-07ee12e0e297.png)

Excuse me if i am wrong.
Thank you

**Comment by jmhbnz** [comment]
Hey @kwangh taking a look at this I think what you might be missing is that in 6.2 there is a new (fourth) node added.  As noted in the explanation under the diagram this increases the quorum required from 2 to 3, however only two nodes in the cluster are actually active meaning it does not have quorum.

@ahrtr I think we can close this issue but can you double check? Thanks! 🙏🏻

**Comment by kwangh** [comment]
@jmhbnz I understand that the cluster has not met the quorum size requirement and it is because the new etcd member is added.
However what I was confused about was the cluster quorum size is 3 therefore it requires minimum 2 active followers to operate. (1 leader and 2 follower) Therefore I thought, requires (at least) 2 active followers, ... was right at first. But you are right, 3 active followers is also right if you focuse on the cluster size ;)

Thank you

**Comment by ahrtr** [comment]
Thanks both @kwangh and @jmhbnz . 

We can close this issue. @spzala
