### ISSUE TITLE
Update CNCF Landscape Summary Table with etcd details

### ISSUE THREAD

**Issue by siforster** [etcd-io/website#658]
Hi All,

The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and include further information about CNCF projects for the wider cloud native community. We would like to request the etcd project submit a PR to the CNCF Landscape repository with additional details that will help further inform the community about your project and its use cases through the popular landscape and this new addition.

The table is located here: https://landscape.cncf.io/summary
There are directions located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

Many thanks for this - we hope it will help further get the word out about your project.

Simon Forster
CNCF Business Value Subcommittee

**Comment by jmhbnz** [comment]
Hey @siforster I'm happy to pick this up.

@ahrtr , @ptabor , @serathius, @spzala  - Below is a draft diff for this update, can you please let me know what you think?  Once we're happy I'm happy to raise the pr for cncf/landscape:

```diff
               incubating: '2018-12-11'
               graduated: '2020-11-24'
               dev_stats_url: https://etcd.devstats.cncf.io/
-              artwork_url: https://github.com/cncf/artwork/blob/master/examples/incubating.md#etcd-logos
+              artwork_url: https://github.com/cncf/artwork/blob/master/examples/graduated.md#etcd-logos
               stack_overflow_url: https://stackoverflow.com/questions/tagged/etcd
               mailing_list_url: https://groups.google.com/forum/?hl=en#!forum/etcd-dev
-              slack_url: https://freenode.net/
+              slack_url: http://slack.k8s.io/
               chat_channel: '#etcd'
               clomonitor_name: etcd
+              summary_personas: Architects, Platform Engineers, SREs
+              summary_tags: distributed, key-value, consistent, datastore, reliability
+              summary_use_case: >
+                Etcd is a distributed, reliable key-value store for the most critical data of a distributed system.
+
+                By using etcd, developers can ensure that their applications have access to up-to-date configuration data, eve
n as they scale up or down, and can maintain consistency, fault tolerance and coordination across multiple instances of the app
lication.
+              summary_business_use_case: >
+                Etcd can be used by businesses to manage the configuration data and coordination needs of their cloud-native a
pplications, ensuring consistent and reliable performance at scale.
+              summary_release_rate: Every 3 months
+              summary_integrations: Due to etcd's flexible and extensible architecture it has been integrated as a data store 
for many projects such as Kubernetes, CoreDNS and Hashicorp Vault.
+              summary_intro_url: https://etcd.io/docs/v3.6/learning/

```

**Comment by spzala** [comment]
@jmhbnz thanks for working on it. It looks okay to me on a quick look. One comment I would add here is, probably good to remove "cloud-native" in the business use case (`coordination needs of their cloud-native applications..`)  to show a more generic usage. Once you add a PR after hearing thoughts from @ahrtr @serathius we can have a better review. Thanks!

**Comment by ahrtr** [comment]
Thanks @jmhbnz . 

Agreed with @spzala on removing the "cloud-native". 

Another comment is about the release_rate, suggest to change it to "every 1-3 months" to match the reality.

**Comment by jmhbnz** [comment]
Addressed both items above, thank you!

I have raised a pr but left in draft as it's a bit hard to review properly with just the diff above. Feel free to leave any additional feedback directly on the pr 🙏🏻

**Comment by spzala** [comment]
Related PR is merged so closing the issue. Thanks @jmhbnz for the quick PR , @ahrtr for quick review , and @siforster for letting us know!
