### ISSUE TITLE
Add etcd-io/website triage access for etcd project members

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#660]
We recently adopted a new approach for our etcd [community membership](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md) which creates a formal membership ladder with defined roles for the project, and incentivizes contributors to work towards roles by providing privileges along with responsibilities at each level. 

At the base `Member` level one of those privileges (and in turn responsibilities) is having triage access to the etcd project. This gives Members more autonomy and eases the burden for maintainers.

When we set up this triage access for project included the following projects were included: https://github.com/orgs/etcd-io/teams/members/repositories 

- `etcd-io/bbolt` 
- `etcd-io/dbtester`
- `etcd-io/etcd` 
- `etcd-io/gofail` 
- `etcd-io/raft`

I would like to propose with this issue that this `etcd-io/website` repository is included in the list.  For some contributors that still have a lot to learn in terms of etcd core code (myself included!) having other areas to contribute towards like our docs helps provide more learning pathways while still making improvements for the etcd project overall.

Adding triage access for `etcd-io/website` to the `Member` role would further reduce burden for maintainers also, for example minor issues that have been addressed would be able to be closed by the member without needing to bug a maintainer. A good example is here: https://github.com/etcd-io/website/issues/567.

Maintainers @ahrtr , @serathius , @spzala , @mitake, @ptabor please let me know what you think 🙏🏻

**Comment by serathius** [comment]
No problem
