### ISSUE TITLE
Confirm maintainership for etcd website

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#679]
Currently it is not fully clear who is an etcd website maintainer because:
- the github etcd `maintainers-website` team does not have any members populated, refer: https://github.com/orgs/etcd-io/teams/maintainers-website 
- there is no `MAINTAINERS` file included at the root level of the repo.

This can create friction for pull requests because contributors don't know who they need to ping if they have questions or want help with a contribution.

I would like to use this issue to request overall etcd maintainers please confirm the list of people that should be website maintainers and update this into the github team.  I also think we should consider adding a `MAINTAINERS` file here as many people just look for that file and it would align this repo with other etcd project repos.  I'm happy to raise the pr if maintainers agree.

**Comment by jmhbnz** [comment]
cc @etcd-io/maintainers-etcd

**Comment by ahrtr** [comment]
As a start point, we can add all existing etcd maintainers as the website's maintainers, just in the same way as we did for other repo, e.g. bbolt, raft. 

cc @mitake @ptabor @serathius @spzala

**Comment by spzala** [comment]
+1 @ahrtr

**Comment by jmhbnz** [comment]
Closing - maintainer file was merged in https://github.com/etcd-io/website/pull/691 and [maintainers-website](https://github.com/orgs/etcd-io/teams/maintainers-website) github team has been populated 🎉
