### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by vincebrannon** [etcd-io/website#696]
Defragmentation is issued on a per-member so that cluster-wide latency spikes may be avoided.

Should read:

Defragmentation is issued on a per-member **BASIS** so that cluster-wide latency spikes may be avoided.

**Comment by jmhbnz** [comment]
Hey @vincebrannon - Thanks for reporting this. I agree the wording is a bit off.

A quick scan shows these files as impacted:

```bash
 james  ~  D  website   main ↑3                                                                                          14:28:38 
 ➜ grep -Ril "Defragmentation is issued on a per-member so that cluster-wide latency spikes may be avoided." | sort -h
content/en/docs/v3.1/op-guide/maintenance.md
content/en/docs/v3.2/op-guide/maintenance.md
content/en/docs/v3.3/op-guide/maintenance.md
content/en/docs/v3.4/op-guide/maintenance.md
content/en/docs/v3.5/op-guide/maintenance.md
content/en/docs/v3.6/op-guide/maintenance.md
```

Please feel free to open a pull request to sort this out, we welcome new contributors! I'm happy to help with questions 🙂

**Comment by jmhbnz** [comment]
Completed in #728.
