### ISSUE TITLE
Migrate etcd docs to website repo

### ISSUE THREAD

**Issue by spzala** [etcd-io/website#7]
Migrate the content of https://github.com/etcd-io/etcd/tree/master/docs to this new repo. Adding more details later working with @gyuho

**Comment by spzala** [comment]
@gyuho @hexfusion please let me know if you have any thoughts here. Thanks!

**Comment by lucperkins** [comment]
This has already been done (#8). Let me know if this is more or less what you had in mind. You can see the current state of the new site at https://etcd.netlify.com.

**Comment by spzala** [comment]
OK, cool. Thanks @lucperkins
