### ISSUE TITLE
Update community meeting website page following survey

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#703]
As mentioned at our community meeting 29th June we would like your input on adjusting our community meeting frequency, length and time.

We have issued a survey asking for feedback as our last few meetings have all had a lot of topics and we have run out of time.

This issue should be updated to summarise the survey feedback and then propose any changes to our community website page: https://etcd.io/community

**Comment by jmhbnz** [comment]
Here are the initial survey results, I'm not expecting much change in these numbers:

![image](https://github.com/etcd-io/website/assets/39425256/f3bc9450-4ccf-4a76-bff0-6e402769e929)

![image](https://github.com/etcd-io/website/assets/39425256/9cfca170-15d6-46b9-a3d2-e0c283b6eaba)


And for timezones responses were grouped under:

- EET - Eastern Europe Time
- CST - China Standard Time
- PST - Pacific Standard Time
- CET - Central European Time
- NZST - New Zealand Standard Time

Although I believe we need to add the UK to that list.  Doing a quick comparison there is no way for all timezones to win:

![image](https://github.com/etcd-io/website/assets/39425256/d0bccdcf-deb3-48fb-8b96-a78b090dd733)


cc @ahrtr, @serathius  for your thoughts.  It looks like we are definitely moving to 30 minutes once a fortnight, we just need to decide if we are changing time also.  Personally I don't mind it where it is.

**Comment by serathius** [comment]
The time for me is okish, would prefer a an hour or two earlier, but it's not a big deal. 

I can update the meeting to once a fortnight, but before that @jberkus can you confirm if the zoom migration is ready?

**Comment by ahrtr** [comment]
+1 with once a fortnight. 

Regarding the timezone, I am good as long as it's between 9:00 AM ~ 9:00 PM UK time.

**Comment by pchan** [comment]
> The time for me is okish, would prefer a an hour or two earlier, but it's not a big deal.

+1 to meeting being earlier, as the current one falls on 11:30 p.m. IST.

**Comment by ahrtr** [comment]
Adding my comment https://github.com/etcd-io/etcd/pull/16189#discussion_r1254132793

**Comment by jmhbnz** [comment]
Closing -  required website updates following decision from survey to go to fortnightly meeting schedule were completed.
