### ISSUE TITLE
Document `--auth-token` flag

### ISSUE THREAD

**Issue by twz123** [etcd-io/website#706]
etcd-io/etcd#16174 adds support for for the EdDSA JWT signing algorithm. While reviewing that PR, it turned out that the whole flag needs to be documented: https://github.com/etcd-io/etcd/pull/16174#issuecomment-1621442836.

**Comment by edragone** [comment]
I'm interested in working on this

**Comment by nate-double-u** [comment]
Thanks @edragone, assigned!

**Comment by jmhbnz** [comment]
Closing, completed in #746.
