### ISSUE TITLE
Upgrade Hugo

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#717]
The current version of Hugo is quite old (0.89.x). The upgrade is best done in not-too-big version leaps, while examining the generated site page diffs to ensure that nothing has been seriously broken.

**Comment by jmhbnz** [comment]
First two version bumps were successful.  Next bump should go to latest release tag in https://github.com/jakejarvis/hugo-extended/tags to close out this upgrade.

Marking as a contribfest issue for next week.

**Comment by sgotand** [comment]
contribfest: let me try take on this issue

**Comment by nate-double-u** [comment]
Hi @sgotand, thanks for helping out!

**Comment by sgotand** [comment]
Due to https://github.com/gohugoio/hugo/pull/9190, current theme docsy is broken.

**Comment by nate-double-u** [comment]
Let me take a look. We may need to update docsy (and we should), but that's a much more involved process.

**Comment by nate-double-u** [comment]
Thanks for updating the report @sgotand, it was good meeting you at the etcd Contribfest!

**Comment by nate-double-u** [comment]
Blocked by https://github.com/etcd-io/website/issues/718

**Comment by nate-double-u** [comment]
fixed by: https://github.com/etcd-io/website/pull/803
