### ISSUE TITLE
Upgrade Docsy

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#718]
Docsy has had a number of fixes and improvements since it was last updated. By updating we'll fix #498, among other things. As was mentioned in #717, the upgrade is best done in not-too-big version leaps, while examining the generated site page diffs to ensure that nothing has been seriously broken.

**Comment by nate-double-u** [comment]
I took a look at updating this as a Hugo module, but after having chatted with @chalin, I think that's the wrong path. Probably we should move this from being a git submodule to being an npm install.

**Comment by nate-double-u** [comment]
Currently the site pulls docsy in from a CNCF Fork of docsy found here: https://github.com/cncf/docsy/tree/etcd.io

We can update in place there, but should eventually obsolete it by bringing Docsy in via NPM.

**Comment by nate-double-u** [comment]
fixed by: https://github.com/etcd-io/website/pull/803
