### ISSUE TITLE
Broken link for "etcd/client/v2"

### ISSUE THREAD

**Issue by MoriGM** [etcd-io/website#723]
Link on page https://etcd.io/docs/v3.5/integrations/ is broken for "etcd/client/v2".

**Comment by jmhbnz** [comment]
Hey @MoriGM - Thanks for raising this. Based on the context in https://github.com/etcd-io/etcd/commit/be7be348002002ba7e7b9b98dba926b4d3eb050e I believe the following action should happen:


|Page|Action|
|---|---|
|https://etcd.io/docs/v3.4/integrations/| Update link to https://github.com/etcd-io/etcd/tree/release-3.4/client/v2 |
|https://etcd.io/docs/v3.5/integrations/| Update link to https://github.com/etcd-io/etcd/tree/release-3.5/client/v2 |
|https://etcd.io/docs/v3.6/integrations/| Remove link, library is now internal only for 3.6. |

**Comment by jmhbnz** [comment]
> Hi @jmhbnz - I am working on this issue. I find that link https://github.com/etcd-io/etcd/tree/release-3.4/client/v2 is non-existent. Should this point to https://github.com/etcd-io/etcd/tree/release-3.4/client?

Yes that looks correct for 3.4, thanks 🙏🏻

**Comment by jmhbnz** [comment]
Thanks @fykaa - Closing 🎉
