### ISSUE TITLE
Add missing triage permissions for reviewers-etcd

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#730]
Hey @etcd-io/maintainers-etcd can someone please review permissions differences between the two groups:

- https://github.com/orgs/etcd-io/teams/members
- https://github.com/orgs/etcd-io/teams/reviewers-etcd

It appears that after becoming a reviewer and moving to the `reviewers-etcd` github team I have lost triage permissions on `etcd-io/website`. For example I can no longer label issues or assign reviewers for pr's here. Given how closely linked the two repositories are I believe it makes sense for triage permissions to be granted for both.

**Comment by serathius** [comment]
Oh, I think someone cleaned up permissions. I have kept reviewers as also members so etcd-reviewers team didn't have much permissions. Looks like someone cleaned up reviewers.

To fix it I have made members a parent team of reviewers-etcd. Which means reviewers-etcd inherit all the permissions from members. Please let me know if that fixed the issue.

**Comment by ahrtr** [comment]
Last time when we added @fuweid as a new reviewer, I removed him from the member team. I noticed that @jmhbnz was also in the member team, so remove @jmhbnz as well. @jmhbnz @fuweid I just wanted keep both of you in the reviewer team. Sorry for the inconvenience.

**Comment by serathius** [comment]
No problem, sorry for making it unclear. It should work now 
![image](https://github.com/etcd-io/website/assets/5873433/1261fd97-641f-4a60-bdd4-d215a3e991a5)

@jmhbnz PTAL

**Comment by jmhbnz** [comment]
All sorted now, many thanks team 🙏🏻

**Comment by fuweid** [comment]
Thanks!
