### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by philip-w-howard** [etcd-io/website#738]
The documentation page didn't seem to answer the question, "What is etcd?" It started with "How do I install it?". But if I don't know what it is, how can I know if I want to install it?

**Comment by serathius** [comment]
![image](https://github.com/etcd-io/website/assets/5873433/29dfd7d0-d1aa-4896-92ee-4832f9f36fcf)

**Comment by jmhbnz** [comment]
Hey @philip-w-howard - Thanks for raising this question.  I'm guessing you landed on a docs subpage directly from a google result perhaps. In this situation if you have really foundational questions it's generally best to head back to the site homepage.

I'm going to close this as not planned as the basic question of "_What is etcd?_" is handled well via our main landing page https://etcd.io
