### ISSUE TITLE
Docs for AWS say "across at least two AZs", shouldn't that be three?

### ISSUE THREAD

**Issue by cakoose** [etcd-io/website#74]
In the "Availability" section of https://etcd.io/docs/v3.4.0/platforms/aws/

> In the context of an etcd cluster this means a cluster must contain a minimum of three members where EC2 instances are spread across at least two AZs in order for an etcd cluster to be considered highly available at a Regional level.

If we spread our three etcd nodes across two AZs, then one AZ will have two nodes.  If that AZ goes down, etcd will be completely unavailable, right?

Am I misunderstanding the terms here?

**Comment by geoffcline** [comment]
👀 I'll take a look

**Comment by patrocinio** [comment]
Hello @cakoose You are right: it should say at least 3 AZs.

**Comment by patrocinio** [comment]
Hey @cakoose I see the Platform pages have been removed from recent documentation version (v3.5 and v3.6), and that v3.4 is not being maintained, so it seems this issue is outdated.

Thanks
