### ISSUE TITLE
Update website community page to mention fortnightly triage meeting

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#745]
Recently we started a fortnightly triage meeting for the etcd project that re-uses our standard fortnightly community meeting zoom details but just occurs on alternate weeks to the main community meeting.

We should update our website community and triage pages to mention the new meeting:
 - https://etcd.io/community
 - https://etcd.io/docs/v3.6/triage/issues
 - https://etcd.io/docs/v3.5/triage/issues

These files are located under `content/en/community` and `content/en/docs` in the repo, lets update them to advertise and ensure we get as many people along to our fortnightly triage meeting as possible.

**Comment by mjlshen** [comment]
I can help with this

**Comment by nate-double-u** [comment]
Hi @mjlshen, thanks for helping out!
