### ISSUE TITLE
Search is not working for me

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#752]
A quick issue to record that search did not work for me today and was throwing js errors in console.

```bash
main.min.3bff53fa2e8d9a2c4d0b3eeea5987ff2f2cc9a0f4eccb730274827d5e7cd5538.js:1 Uncaught TypeError: o.popover is not a function
    at o (main.min.3bff53fa2e8d9a2c4d0b3eeea5987ff2f2cc9a0f4eccb730274827d5e7cd5538.js:1:2440)
    at HTMLInputElement.<anonymous> (main.min.3bff53fa2e8d9a2c4d0b3eeea5987ff2f2cc9a0f4eccb730274827d5e7cd5538.js:1:1993)
    at HTMLInputElement.dispatch (jquery-3.5.1.min.js:2:43090)
    at v.handle (jquery-3.5.1.min.js:2:41074)
```

This is probably related to recent upgrades to hugo-extended and we should probably finish the journey of updating docsy in #748 and #718 before we spend any time debugging this.

**Comment by fykaa** [comment]
I could work on this!

**Comment by jmhbnz** [comment]
Hey @fykaa - As mentioned above I think we will hold off any investigation of this issue until we have finished the linked docsy upgrade.  If you are keen to help with upgrading docsy please reach out to @nate-double-u 🙏🏻

**Comment by jmhbnz** [comment]
Closing - Using same browser it appears to be working for me again. Issue was likely limited to my device.
