### ISSUE TITLE
refresh changs value when does not set value

### ISSUE THREAD

**Issue by dingkegithub** [etcd-io/website#76]
website doc "You cannot update the value of a key when refreshing it."

$ curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d value=bar -d ttl=60
{
    "action":"set",
    "node":{
        "key":"/foo",
        "value":"bar",
        "expiration":"2020-09-24T02:17:05.5974668Z",
        "ttl":60,
        "modifiedIndex":12038,
        "createdIndex":12038
    }
}

$ curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true

{
    "action":"update",
    "node":{
        "key":"/foo",
        "value":"",                                                                   // node value refreshed with blank string
        "expiration":"2020-09-24T02:17:18.6460187Z",
        "ttl":60,
        "modifiedIndex":12039,
        "createdIndex":12038
    },
    "prevNode":{
        "key":"/foo",
        "value":"bar",
        "expiration":"2020-09-24T02:17:05.5974668Z",
        "ttl":47,
        "modifiedIndex":12038,
        "createdIndex":12038
    }
}

**Comment by jmhbnz** [comment]
Hey @dingkegithub - Apologies you did not receive a timely response to this issue, the etcd project has not had enough active contributors to respond to all issues.

Taking a quick look at this now while doing some cleanup I can see this is relating to the [docs for etcd v2.3](https://etcd.io/docs/v2.3/api/#refreshing-key-ttl) and specifically the v2 api.  As the project has moved on from the v2 API and release 2.3 is no longer supported I will close this issue.
