### ISSUE TITLE
Add missing backslash in persistent-storage-files.md

### ISSUE THREAD

**Issue by kimsehwan96** [etcd-io/website#826]
Both of v3.5, v3.6 document in learning/persistent-storage-files, there is missing backslash in example command with protoc

https://etcd.io/docs/v3.5/learning/persistent-storage-files
https://etcd.io/docs/v3.6/learning/persistent-storage-files

<img width="1041" alt="스크린샷 2024-04-02 오후 3 49 47" src="https://github.com/etcd-io/website/assets/59886140/37ba266e-f292-48a0-a4b8-e8368d9e6577">

So if use that command directly then you can see error like this `zsh: command not found: -I`

**Comment by jmhbnz** [comment]
Thanks for letting us know about this and raising the fix @kimsehwan96!

/assign @kimsehwan96
