### ISSUE TITLE
Docs -> Learning -> etcd3 API links broken at v3.5 and v3.4

### ISSUE THREAD

**Issue by Kurt212** [etcd-io/website#830]
Looks like https://etcd.io/docs/v3.5/learning/api/ and https://etcd.io/docs/v3.4/learning/api/ pages have broken links
Examples, how it currently looks like:
<img width="787" alt="image" src="https://github.com/etcd-io/website/assets/12201131/712da5ff-d508-4b3f-bab9-2dd1341978b1">
<img width="793" alt="image" src="https://github.com/etcd-io/website/assets/12201131/a20c7d87-1022-4378-8aab-3fd1e74e5cfe">
The problem is this extra '+' sign here https://github.com/etcd-io/website/blob/main/content/en/docs/v3.4/learning/api.md?plain=1#L480
Because of it, this code is not parsed as links, but as plain text:
<img width="850" alt="image" src="https://github.com/etcd-io/website/assets/12201131/0356db6c-ceb9-4e5c-96d3-1b0b057f9cc4">

**Comment by Kurt212** [comment]
Made a quick fix in https://github.com/etcd-io/website/pull/831

**Comment by jmhbnz** [comment]
Thanks for letting us know about this and raising the fix @Kurt212 🙏🏻 

/assign @Kurt212
