### ISSUE TITLE
documentation install.md - clone instructions - branch vs tag

### ISSUE THREAD

**Issue by dulhaver** [etcd-io/website#835]
I am trying to follow the instructions @**https://etcd.io/docs/v3.5/install/** to build etcd manually

I fail on the cloning   
`$ git clone -b v3.5.12 https://github.com/etcd-io/etcd.git` , but can do it with 
`$ git clone -b release-3.5 https://github.com/etcd-io/etcd.git` (`branch` instead of `tag`). 

Somehow I feel it should be `branch` generally, not `tag`.

It that is so I'd try to  create a PR for that change in https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/install.md

**Comment by jmhbnz** [comment]
Hi @dulhaver - Thanks for your question. Running `git clone -b v3.5.12 https://github.com/etcd-io/etcd.git` works for me and should work in any modern `git` version. Can you please be more specific on what error you receive when attempting to clone the repository?

Cloning the tag is the intended approach as we want to refer to a specific release, not `release-3.5` which is a branch that may have work in progress not yet ready for release.

**Comment by ivanvc** [comment]
Related to: https://github.com/etcd-io/etcd/discussions/17894

I think the error that @dulhaver is reporting, is not really an error, but an info log from git, stating that the HEAD for a tag is detached.

**Comment by jmhbnz** [comment]
> Related to: [etcd-io/etcd#17894](https://github.com/etcd-io/etcd/discussions/17894)
> 
> I think the error that @dulhaver is reporting, is not really an error, but an info log from git, stating that the HEAD for a tag is detached.

Thanks for the context - so in this case this is the expected/normal behavior when cloning a tag and is something controlled by `git` not by etcd project.

We need to stick with cloning a tag as etcd users need to clone released code, not the branch HEAD (unless they want latest unreleased changes and know what they are doing).

Closing as I don't believe any changes are required, please let me know if I am missing anything.
