### ISSUE TITLE
Update website community page to reflect robustness meetings

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#850]
We recently introduced biweekly meetings for etcd robustness. Details are available in this pr: https://github.com/kubernetes/community/pull/7892.

We should update https://etcd.io/community page to reflect this so as many people as possible know the meetings are happening and can join in.

Given there are now three meetings we should probably update the page to have a table or bullet points so it is easy to read and understand that there are three types of meetings happening. Additionally we should ensure it is clear on the page we invite community members to propose items for the meetings.

This will require an update to `content/en/community/_index.md`.

cc @serathius

**Comment by thedtripp** [comment]
I'd like to work on this issue.

**Comment by thedtripp** [comment]
I have opened a PR here: https://github.com/etcd-io/website/pull/853

**Comment by jmhbnz** [comment]
Completed in #853 - Thanks @thedtripp
