### ISSUE TITLE
Adding a .NET library

### ISSUE THREAD

**Issue by i4004** [etcd-io/website#855]
Hi! We have a .NET etcd based configuration provider for `Microsoft.Extensions.Configuration` (a default .NET library for working with configuration). It can be included in "Libraries and tools" section in .NET libraries list.

The link: https://github.com/SimplifyNet/Etcd.Microsoft.Extensions.Configuration

**Comment by jmhbnz** [comment]
Hey @i4004 - Thanks for this suggestion. Taking a quick look it doesn't seem like there has been any maintenance to this library for a couple of years, is it still maintained?

**Comment by i4004** [comment]
Hi! Yes, there was no commits, but I am planning a new release soon.

**Comment by i4004** [comment]
The new version has been released :)

**Comment by jmhbnz** [comment]
Thanks @i4004 - Please feel free to raise a pr adding this to the site.

**Comment by i4004** [comment]
Done: https://github.com/etcd-io/website/pull/858
