### ISSUE TITLE
Enable Markdown linting

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/website#857]
Currently, the repository doesn't have a Markdown linter. This causes PRs sometimes to discuss using Markdown standards and contributes to a drift in discussions. Following what we recently discussed in a PR (https://github.com/etcd-io/website/pull/774#discussion_r1498552258). Enabling linting for the whole repository may require a significant effort. I think a good starting point would be to incrementally run a Markdown linter against the changes from pull requests.

**Comment by ivanvc** [comment]
I'll reopen this issue until we have the prow job working.

**Comment by ivanvc** [comment]
The job didn't work because the base node image uses `mawk` instead of `gawk`. I have a fix for this, which requires a change in the prow job (install gawk) and a change in the script from this repo (to use `gawk` instead of `mawk`). This fix is straightforward and needs two pull requests.

However, after seeing the result from the prow job. GitHub's output was more evident on where the linting issues were. Please refer to run [1827137607608307712](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/etcd-io_website/885/pull-website-lint/1827137607608307712) from my test PR #885.

Even though I'm using red in the terminal, the error lines are shown in yellow, and the warnings are shown in white. I'm considering errors violations in edited fragments/changed ranges, and warnings are violations in the edited files but not in the changed ranges.

I'm considering two options to improve the output:

1. Group errors and warnings in different sections and add some description text.
2. Only display the errors.

@jmhbnz, WDYT?

**Comment by jmhbnz** [comment]
> I'm considering two options to improve the output:
> 
>     1. Group errors and warnings in different sections and add some description text.
>     2. Only display the errors.

I am not worried by the output colors if necessary we can provide guidance to folks raising pr's if they don't understand the output.

The inclusion of linting is a great step forward to gradually improve & standardise the docs over time. Let's see how it goes as is.  The change re `gawk` sounds good.

**Comment by jmhbnz** [comment]
Discussed at sig-etcd triage meeting, lets use this issue to add to the linting configuration and progress the prow job to blocking.

**Comment by ivanvc** [comment]
@jmhbnz, these are the configurable rules from the Markdown linter: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

For example, in PR https://github.com/etcd-io/website/pull/893 the linter didn't like the [consecutive line breaks](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/etcd-io_website/893/pull-website-lint/1833589599985733632) ([MD012](https://github.com/DavidAnson/markdownlint/blob/main/doc/md012.md)). Should we disable MD012?

Also, because the job is not blocking, the prow bot didn't show the error as a comment. Should we mark it as blocking so it's more evident?

**Comment by jmhbnz** [comment]
Let's proceed with blocking for the job. 

In relation to my above comment about tuning the linting config on second thought I'm thinking we should probably keep the standard rules until something becomes really problematic.

Let's close this issue once the job is blocking.
