### ISSUE TITLE
Option headers in configuration guide transform `--` into an en-dash

### ISSUE THREAD

**Issue by johnson-earls** [etcd-io/website#870]
The "Configuration Options" page at https://etcd.io/docs/v3.4/op-guide/configuration/ is quite confusing, as the section headers with the option names use `&ndash;` instead of `--`, making it look like etcd wants a single dash rather than a double dash.

**Comment by jmhbnz** [comment]
Thanks @johnson-earls for reporting this. Discussing during sig-etcd triage meeting, assigned to @moficodes to investigate a fix.

/assign @moficodes

**Comment by moficodes** [comment]
@jmhbnz Looks like in 3.5 we bypass this problem by grouping flags in codeblocks. https://etcd.io/docs/v3.5/op-guide/configuration/

Version <=3.4 all have the same issue. 

So I can either change all the instance of 

### --flag
to 

### `--flag`


Or change how hugo renderes -- as endash.

Its a setting we can change.
