### ISSUE TITLE
Add WG etcd operator community meetings to community section

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/website#896]
Add a WG etcd operator section in the community page ([content/en/community/_index.md](https://github.com/etcd-io/website/blob/main/content/en/community/_index.md)).

The meetings are scheduled biweekly on Tuesdays at 11 a.m. PT. The Zoom details are the same as the Robustness and Community/Triage meetings.

**Comment by jmhbnz** [comment]
Completed - Thanks @danish9039 🙏🏻
