### ISSUE TITLE
Update robustness meeting time

### ISSUE THREAD

**Issue by jmhbnz** [etcd-io/website#917]
As outlined in https://github.com/kubernetes/community/pull/8165 we are moving the fortnightly robustness team meeting to `11:00 PST` in line with our other meetings.

This needs to be updated in https://etcd.io/community.

**Comment by samuelbartels20** [comment]
@jmhbnz Please assign this issue to me

**Comment by jmhbnz** [comment]
Completed in https://github.com/etcd-io/website/pull/922, thanks @samuelbartels20
