### ISSUE TITLE
Migrate documentation: Remove docs from etcd-io/etcd

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#97]
## Description

As per the conversation around the [Etcd.io Docs/SEO Improvement Plan](https://github.com/etcd-io/website/issues/65):

Replace existing documentation in [etcd-io/etcd](https://github.com/etcd-io/etcd) repo with signposts to new location on website (etcd.io).

## Deliverable

[etcd-io/etcd](https://github.com/etcd-io/etcd) Documentation folder points to etcd.io/docs

## Notes

- Since we agreed that issues related to the etcd.io Docs/SEO Improvement Plan should be made in the [etcd-io/website](https://github.com/etcd-io/website) repo, this issue is being created here even though it affects [etcd-io/etcd](https://github.com/etcd-io/etcd)
- The pull request for this issue will be made in [etcd-io/etcd](https://github.com/etcd-io/etcd)
- The pull request for this issue in [etcd-io/etcd](https://github.com/etcd-io/etcd) should not be merged until the PR for [Migrate documentation: Add docs to etcd-io/website #93](https://github.com/etcd-io/website/issues/93) has been merged. PR https://github.com/etcd-io/website/pull/99

- https://docs.google.com/spreadsheets/d/1-ZQMPc_eQ0fh1pwOHv3NltwT-ifKA5UcFePfdFiWn8I/edit?usp=sharing

**Comment by nate-double-u** [comment]
/cc @spzala @jberkus 

I think removal of these docs from the [etcd-io/etcd](https://github.com/etcd-io/etcd) repo can go a couple ways:
1. [Dex IdP model](https://github.com/dexidp/dex/pull/1810): where all the .md files were removed, and the top level documentation/README.md was altered with a note that the documentation files had moved to the website repo
2. [CNI Plugins model](https://github.com/containernetworking/plugins/pull/549): where each individual file that got moved was edited with a link to its new home on the website.

**Comment by rohitdurvasula** [comment]
@nate-double-u  any idea where does the etcd-mixin folder inside Documentation folder now reside ?

https://github.com/prometheus-operator/kube-prometheus used to depend on that.

**Comment by spzala** [comment]
@rohitdurvasula ah, here, https://github.com/etcd-io/website/tree/master/content/docs/current/etcd-mixin Thanks!

**Comment by nate-double-u** [comment]
If that location doesn't work and it needs to be back in this repo, let us know and we can see about restoring it. There are still a couple folders/files that have stayed in the Documentation folder here as they are a part of an automated system.

**Comment by underrun** [comment]
this breaks installs of kube-prometheus and anyone else who may have depended on that jsonnet library.

really it was never documentation... please restore it :-)

**Comment by nate-double-u** [comment]
I'll open a new PR to restore `etcd-mixin` shortly

**Comment by nate-double-u** [comment]
> really it was never documentation...

We may want to open a separate issue at some point to move this out of the `Documentation` folder -- if it isn't documentation it's probably in the wrong spot.

**Comment by spzala** [comment]
@nate-double-u yeah, we should. And also, we can comment it in the files about how they are being used.
